### ISSUE TITLE
"Availability" Feature Test for "Physical Holdings in Temp Locations" randomly fails

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/orangelight#1046]
The following test was passed only after attempting to rebuild on Travis CI for the same branch several times:

https://github.com/pulibrary/orangelight/blob/master/spec/features/availability_spec.rb#L35

**Comment by kevinreiss** [comment]
This one depends on a live bibdata response. The randomness is likely to due to intermittent http failures. The purpose of the feature test was to make sure the temporary reserve location information was properly filtered through the availability.js.coffee.erb that calls bibdata for https://bibdata.princeton.edu/availability?id=7917192.

**Comment by hackmastera** [comment]
related to #1094

**Comment by jrgriffiniii** [comment]
I believe I have resolved this on my branch for https://github.com/pulibrary/orangelight/pull/1038 , please see https://github.com/pulibrary/orangelight/pull/1038/commits/b4c00079d1438d8b948a7f0d4dfbf2b9b3460eeb#diff-817bcaeba4499643e72705c701683a41

**Comment by christinach** [comment]
we dont see this issue any more
