### ISSUE TITLE
Real Time Availability on Index View

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#107]
For non-serials think about doing this directly against Voyager item record. Serials display only holdings level information w/stackmap or offsite link. Records with digital surrogates should provides these links on the index view. What non-Voyager records do here?

**Comment by jpstroop** [comment]
If we're going to do this,  I think the bibdata app should allow you to
POST an array of IDs so that it doesn't,  e.g. get hammered with requests
when someone sets their rpp to 50.

Thoughts?

Also, the client will need to know when to ask for additional info about a
serial. There are plenty of potential hooks in the MARC record for this,
but we'll need to make sure there's something actionable in the search
results.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by kevinreiss** [comment]
We can implement this on show for the first pass but I definitely think doing the RTA for non-serials is something we want to do for the index view via an async call(s). It is one of the chronic complaints from staff that Primo doesn't do a good job of this.

How clunky is it on the oracle side to manage a web request that would return item data for an array of IDs in a single call.

**Comment by jpstroop** [comment]
> How clunky is it on the oracle side to manage a web request that would return item data for an array of IDs in a single call.

It will take _n_ separate queries, but at least I'd be able to use the same connection. Getting item info is already less than ideal:

https://github.com/pulibrary/marc_liberation/blob/development/voyager_helpers/lib/voyager_helpers/queries.rb#L21-L46

and that's after I've retrieved the mfhd ids for the bib id, and the item ids associated with each mfhd:

https://github.com/pulibrary/marc_liberation/blob/development/voyager_helpers/lib/voyager_helpers/queries.rb#L138-L151

The item ids aren't in the MARC data, so we're talking about a minimum of three queries per title, and often several more.

**Comment by kevinreiss** [comment]
Since we are indexing holdings data and know the format of the records. I think we'd be able to limit the real time requests to queries for only bib ids that are single holding/single item records. There might be a few exceptions but for large part that would be it. We could further narrow it down by ignoring records that have only have holdings in online locations.

**Comment by jpstroop** [comment]
Yes, at least asking the user to click something to make the request explicit. ("Multiple Holdings. [Check Availability]()") Something like that.

**Comment by tampakis** [comment]
Pull the availability from bibdata, example url: http://bibdata.princeton.edu/availability?ids[]=3377193&ids[]=4679943&ids[]=857469&ids[]=12324&ids[]=7617477

If the more_holdings value is true, then the item has more than 2 holdings. This means that instead of showing the actual holdings, "Multiple Holdings" is displayed. For now, I think we should have the user click on the record to get more detailed availability.

The other keys are location codes which are stored in solr as `location_code_s`. They match up (in the same order) with `location` and `call_number_display`. @jpstroop  - Any thoughts on: If the status is "Not charged" show a checkmark, otherwise show an x?

However if we wanted to get more information about the availability without leaving the search results view as mentioned in the above comment, we'd want to pull from the individual record availability service: http://bibdata.princeton.edu/bibliographic/426420/items

**Comment by jpstroop** [comment]
> For now, I think we should have the user click on the record to get more detailed availability.

:+1: An expandy-collapsy thing that keeps you on the page is tempting, but it could start to turn into the mess that is Primo's results page, so let's go w/ click through until someone forces us to do otherwise.

> The other keys are location codes which are stored in solr as location_code_s. They match up (in the same order) with location and call_number_display. @jpstroop - Any thoughts on: If the status is "Not charged" show a checkmark, otherwise show an x?

I not quite understand what you're asking here. I would just show the location label (which you could get from the [location service](http://bibdata.princeton.edu/locations/holding_locations.json), (though I'd cache it, not hit it a bunch of times), and I'd just show "Charged" or "Not Charged"--and not work about a graphic.

There's something else here that your example brings up: I'm not sure if it's a concern here or not. In your [example query](http://bibdata.princeton.edu/availability?ids%5B%5D=3377193&ids%5B%5D=4679943&ids%5B%5D=857469&ids%5B%5D=12324&ids%5B%5D=7617477), for 4679943 we have one in svl, which is a closed location, and the other is at recap. Technically, yes, these are available, but one you can't actually check out, and the other is going to take you 24 hours to get. So, is it really available? Maybe qualify with "Not Charged" with "(Non-Circulating)" for the former...and I guess ReCAP speaks for itself, so maybe that's OK.

Also for that same bib, 4679943, the availability service says `more_holdings: true`, but looking at the [items service](http://bibdata.princeton.edu/bibliographic/4679943/items) for it, there are only those two. I'd expect `more_holdings` to mean "more than [these] two" not "two or more", which doesn't really make sense in this context. See what I mean?

**Comment by tampakis** [comment]
> The other keys are location codes which are stored in solr as location_code_s. They match up (in the same order) with location and call_number_display.

I was explaining the way the availability service would work in the context of Blacklight. Take bib 3377193 for example. It has one holding at "rcpqv". The value for this key in the [example query](http://bibdata.princeton.edu/availability?ids%5B%5D=3377193&ids%5B%5D=4679943&ids%5B%5D=857469&ids%5B%5D=12324&ids%5B%5D=7617477) is "Not charged." However in the Blacklight [search results](http://pulsearch-dev.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=3377193), the holding block [combines](https://github.com/pulibrary/orangelight/blob/development/app/helpers/application_helper.rb#L54-L67) the location and call_number_display fields. The index of the values in the location, call_number_display, and location_code_s arrays correspond to the same holding record. 

Here is an example for a dummy record:
```
Blacklight/Solr:
"location": ["location_holding0", "location_holding1"]
"location_code_s": ["b_h0", "a_h1"]
"call_number_display": ["H 0", "H 1"]

Bibdata:
"a_h1": "Charged"
"b_h0": "Not charged"
```

On page load, Blacklight combines `location` and `call_number_display` to get `H 0 > location_holding0` and `H 1 > location_holding1`. In bibdata, the location codes are in ABC order in the hash. In Blacklight, the order of the location_code_s is matched to the same holding records as the location and call_number_display arrays.

When the javascript will pull in the availability, it needs to know which holding record to add the status message to. It can tell based on the index of the location_code_s array. Hope that it's a bit clearer than before.

> If the status is "Not charged" show a checkmark, otherwise show an x?

Check out this search: https://newcatalog.library.cornell.edu/catalog?utf8=%E2%9C%93&q=stroop&search_field=all_fields

A checkmark (available) or an x (unavailable) is more useful to the user than "Not charged" or "Charged" is. I thought the logic could be as simple as `if status == "Not charged": available, else: unavailable`. It might need to be a bit more involved based on locations (such as for Recap or svl as you mention above).

> Also for that same bib, 4679943, the availability service says more_holdings: true, but looking at the items service for it, there are only those two. I'd expect more_holdings to mean "more than [these] two" not "two or more", which doesn't really make sense in this context. See what I mean?

I should have better explained what more_holdings means. It gets set to true when there are more than 2 holdings records or if any of the first two holding records contains more than 1 item. Maybe I should call it `more_items` instead? I think that a user would be misled if they see a status for a holding, that status is only for the first of many items a record may have. I thought that we wouldn't pull in the statuses for records that have `more_holdings` set to true.

**Comment by kevinreiss** [comment]
Unfortunately the "Not Charged" situation isn't simple enough to always allow you to reliably render a green or red checkmark to indicate a record's availability to the patron.  If you take the total list of voyager item status (27 at last count) you can definitely split them into two areas one that you could are "available" or "not available" (which we probably should document somewhere), but in addition to those there are a ton of records that have holdings only data where you can never definitely say what you can do with them without further review of the service logic from bibdata around the location code. Considering that you've got to add a third case, "Check Further (i.e. More Items)".

My thoughts on how to display this on the search results page would be: 

* Single Holding, Single Item Record, Status=Available - Display Item Status Label with a positive indicator
* Single Holding, Single Item Record,  Status=Unavailable Status - Display Item Status Label with negative indicator and a link to a wider routine that calculates what other request options we might have for the item. 
* Single Holding, Many Item Records, Display Check Further 
* Multiple Holdings, Many Item Records, Display Check Further
* Single Holding, No Item Records , Display Check Further 
* Multiple Holdings, No Item Records, Display Check Further 

Whether "Check Further" should be a collapsy widget that keeps the user on the search results page or sends them to another page I'm not sure. I'd tend towards the latter but could persuaded that we should the try the other one as long as we don't do it with a tab. 

One other thing to consider is a bit of Primo history. I remember that Library staff hated the fact that Primo did not display the item status on the initial search results page (what half those labels mean to non-staff member I have no idea - but that is another question) so we should probably display those in addition to whatever visual effect we use indicate status/availability.

**Comment by jpstroop** [comment]
OK, I think I'm a little clearer.
> On page load, Blacklight combines location and call_number_display to get H 0 > location_holding0 and H 1 > location_holding1.

I'm not sure what ">" this means, but since copy numbers typically start over with holdings, I'd expect to see, e.g.,

    Marquand Library, c. 1 - Not Charged
    Architecture Library, c. 1 - Charged

>> If the status is "Not charged" show a checkmark, otherwise show an x?

> A checkmark (available) or an x (unavailable) is more useful to the user than "Not charged" or "Charged" is...

It's not immediately clear to me at all what that check is supposed to means but I guess it's OK with as long as there is a tooltip as well. It adds some color to the UI and saves space anyway. I think "Missing" is an option as well. We should check the item_status table in Voyager and make sure all of the cases are covered.

Re: `more_holdings`, now I'm even more confused, maybe.

> It gets set to true when there are more than 2 holdings records or if any of the first two holding records contains more than 1 item.

It sounds like these are two separate things, then, though I think I get what you're trying to accomplish.

Case 1: a multi-volume set, or serial. It's not practical to show the availability of each, so you want users to click through so see detailed availability

Case 2: a simple, one volume monograph, of which we have multiple copies, in multiple locations.

I could be wrong, but I think surfacing the difference between these two cases is worth while. And I know we decided on two being a magic number, but I'm not sure why. I think I'd prefer to see "This item has multiple parts, Click for Availability" or "Multiple Copies, Click for Availability", depending on the case.

**Comment by tampakis** [comment]
> I'm not sure what ">" this means, but since copy numbers typically start over with holdings, I'd expect to see
I was trying to replicate what appears on the search results page currently:
![holding_info](https://cloud.githubusercontent.com/assets/4650153/10470542/f4170696-71db-11e5-87f8-f8fac65f56e7.png)
It's call number followed by its location with an arrow like separator. It has nothing to do with items or availability. Having a visual indicator with a tooltip including the status would help keep the display clean.

I think you captured the two cases for "more_holdings" correctly.

**Comment by kevinreiss** [comment]
Here are the Voyager Item Statuses I have in the current app that were deemed "unavailable" by staff.

At Bindery
Claims Returned
Charged
Hold Request
In Transit
Lost
Missing
On Hold
Overdue
Recall Request
Remote Storage Request
Renewed
Withdrawn

**Comment by terrellt** [comment]
Is this API hidden for any reason, or am I welcome to ping it directly via JS?

**Comment by tampakis** [comment]
Bibdata shouldn't be hidden.

**Comment by jpstroop** [comment]
Documentation is, er, lacking, but the routes should help you get started:

https://github.com/pulibrary/marc_liberation/blob/development/config/routes.rb

**Comment by jpstroop** [comment]
Thanks for that list @kevinreiss - it looks like we responded at the same time, but your reponse makes a lot more sense than mine :wink: 

Re:
> > I'm not sure what ">" this means, but since copy numbers typically start over with holdings, I'd expect to see

> I was trying to replicate what appears on the search results page currently:
![holding_info](https://cloud.githubusercontent.com/assets/4650153/10470542/f4170696-71db-11e5-87f8-f8fac65f56e7.png)

Gotcha. It's a much more subtle thing, but I think the template should be {Availability Symbol} {Library}: {Copy No}, e.g.:

:green_heart: Video Library: DVD 718
:red_circle: Firestone Library: DVD 917

(with better Emoji...)

**Comment by terrellt** [comment]
Going to start working on this and see how far I get with the info here.

**Comment by terrellt** [comment]
@jpstroop @tampakis  I've got this working, but I haven't reformatted the display as per @jpstroop's last comment. Do we want that as a separate ticket, or should I shim it in here?

**Comment by tampakis** [comment]
i'll make it a separate ticket, especially since you're adding a spec for that helper method.
