### ISSUE TITLE
Mock client-side bibdata/availability calls

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#1094]
current failing spec: 
https://github.com/pulibrary/orangelight/blob/master/spec/features/request_options_spec.rb#L23

Note this spec doesn't fail on ci because it's excluded from travis.

Related to #1092

**Comment by hackmastera** [comment]
I tried to use the technique discussed in https://github.com/pulibrary/orangelight/issues/656#issuecomment-352900606 but because bibdata's API uses querystrings it wasn't possible without doing routing or controller code which I didn't want to do. The right thing to do is test the ajax responses as desired in javascript unit tests. integration tests should simply ensure that the divs or other data required by the javascript are present.

**Comment by christinach** [comment]
It's not being excluded from ci anymore
