### ISSUE TITLE
490 series title not indexed

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1200]
Searching for series titles of music scores does not work.  For example, this search finds nothing:

https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=stradella+works+ets&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Bformat%5D%5B%5D=Musical+score&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=all_fields&q=Stradella+opera+omnia

But it should retrieve these items:

https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&q1=stradella+works+ets&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&f_inclusive%5Bformat%5D%5B%5D=Musical+score&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search

**Comment by joycebcat** [comment]
@escowles I agree that the 490 should be indexed for KW, but it shouldn't go into title indexes.

**Comment by tampakis** [comment]
It does get indexed ([example](https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=series_title&q1=omnia+di+Alessandro+Stradella&op2=AND&f2=author&q2=&op3=AND&f3=title&q3=&range%5Bpub_date_start_sort%5D%5Bbegin%5D=&range%5Bpub_date_start_sort%5D%5Bend%5D=&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&search_field=advanced&commit=Search)), but the issue is that dell'Opera doesn't get split, so we get no results by searching for opera on it own.

**Comment by escowles** [comment]
Can we add a synonym for "dell'Opera" to "opera" to fix this particular search?

**Comment by joycebcat** [comment]
No, that does nothing to address the underlying issue.  It seems like this is a matter of normalization.  I think you are saying that the apostrophe is removed during normalization, rather than replaced by a space.  For Italian, certainly, replacing it with a space is a better choice.  Should the apostrophe ALWAYS be replaced by a space?  I'm not sure.  What normalization specs are you using for BL indexing?

**Comment by escowles** [comment]
I think we need to revisit https://github.com/pulibrary/orangelight/issues/484 in light of this case, in particular, whether there are less drastic options for addressing that issue that wouldn't remove all apostrophes.

**Comment by joycebcat** [comment]
@escowles @tampakis Ah, I think where you went wrong here was to treat the character in Bratʹi︠a︡ as an apostrophe.  It is the character 02B9.  You can normalize that with no space, but normalize the apostrophe as a space and that should suit all the cases that I can think of at the moment.
