### ISSUE TITLE
Solr Upgrade to 5.1

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#123]
I don't know how soon this should happen but there have been some interesting changes in the last two Solr releases.

First - Solr is now a standalone service (using Jetty internally) and doesn't support Tomcat:
* https://cwiki.apache.org/confluence/display/solr/Running+Solr+on+Tomcat
* https://cwiki.apache.org/confluence/display/solr/Taking+Solr+to+Production

Other features:
* A [DateRange field](https://issues.apache.org/jira/browse/SOLR-6103) (useful for publication date)
* A more powerful [facet query API](http://yonik.com/json-facet-api/) with [sub-facet](http://yonik.com/solr-subfacets/) (pivot facets with more functionality) support 
* [Parameter substitution](http://yonik.com/solr-query-parameter-substitution/)/interpolation

The solr.xml file and cores have to be in autodiscovery mode starting in 5.0.

**Comment by jpstroop** [comment]
Interesting. I have no problem deploying with Jetty (we have other apps that do this), but I hope they provide a good config guide. Jetty has always been severely under-documented. The "Taking Solr to Production" page looks pretty good; it looks like they've encapsulated a lot of Jetty's weirdness (it's not really weird, but it can be very different from what Java servlet fols are used to).

I'll have to look at the DateRange field, but we're we using integers since we only have years? I guess this may come back to bite us at some point, but I'd assuming a less complex type like an int would still offer better performance than  a field specialized  for dates.

Those other features look very cool as well. The different response for facets surprises me a bit, and probably means that Blacklight (and Hydra, for that matter) will take a while to catch up, but it all seems for the better.

I'd say just track Blacklight, and if you see any opportunities to make PRs for Blacklight to get it closer to Solr 5.1 support, go for it.
