### ISSUE TITLE
Display copy numbers

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1445]
Some records have many copies, e.g.: https://catalog.princeton.edu/catalog/2520232

As in this case, there may be notes about the different copies, but there's no way to match those notes with the call number/availability information displayed.

**Comment by escowles** [comment]
That's an interesting idea @christinach — I think simply displaying the copy number in the list of copies would be good enough, but doing a :hover highlight sounds like a good way to make it clear which copy the notes refer to (if we can reliably match them).

**Comment by mzelesky** [comment]
I remember @joycebcat doing a project around this last year, about adding text into the bib records, and other information in holdings records. I don't remember the details though.

**Comment by joycebcat** [comment]
We did a giant project a couple years ago to convert these so they work well in Blacklight.  A hover highlight isn't going to work in many cases.  The background here is that we used to use the location name, or the call number, or the copy number or the item id number, or possibly other things to indicate which copy the note referred to.  Then the objects got transferred to a different location, they went through the reclassification project and their call number changed, or other things happened and the note no longer matches in any discernible way with the correct holding.  We are making explicit connections now between the note and the holdings record.  I sort of knew that not all the lists were finished, but I haven't gotten around to looking at what is left and sorting out a second wave of conversions.  NOTE:  the copy number of any particular item is NOT always the same as the copy number referenced in the copy-specific note.   Please do not add any method for users to see the item copy numbers because that will mess up our notes!

**Comment by mzelesky** [comment]
From Joyce's note above, it sounds like she doesn't want the copy numbers displayed at all, and that it's a project for catalogers to find records that use 'Ex copy 2' etc. to refer to notes, and change the note text.

**Comment by tampakis** [comment]
@joycebcat so we don't ever want to display copy numbers from the holding record?

**Comment by joycebcat** [comment]
@tampakis Correct. The copy number in the mfhd subfield t shouldn’t be displayed.

**Comment by tampakis** [comment]
Thanks @joycebcat. I'll close the issue. Could the copy number info be incorporated the holding record notes for https://catalog.princeton.edu/catalog/2520232?
