### ISSUE TITLE
browse index treatment of initial spaces and non-alphanumeric characters

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/orangelight#146]
@tampakis @jpstroop I discovered in the subject blank browse report that you pulled for me, Nikitas, that almost all the problems were subjects which had an extra space at the beginning of the string, or a non-alphanumeric character.  All the legitimate subject headings for the African people which begins "!Kung" were in this list.

**Comment by tampakis** [comment]
!Kung actually works: http://pulsearch-dev.princeton.edu/browse/subjects?search_field=browse_subject&q=!Kung

The '!' gets stripped but since there are other characters it gets mixed with other 'K's

The problem was I didn't check to see if my queries actually gave back the problem records! I'll send you the correct list.
