### ISSUE TITLE
Embed another institution's manifest in catalog record display

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#1494]
Request from Tom Ventimiglia:

> Is it possible to embed in a Blacklight record a UniversalViewer document from a different institution?  For example, this one from Oxford:
https://iiif.bodleian.ox.ac.uk/iiif/viewer/9b30b95d-c827-490d-a7b6-743a68cde604#?c=0&m=0&s=0&cv=1&r=0&xywh=-4207%2C-1%2C13162%2C6864

I'm marking this as a question so we can discuss the implications of this.

**Comment by jrgriffiniii** [comment]
My hope was that https://github.com/pulibrary/orangelight/issues/1360 would move the approach to indexing away from requiring any caching of IIIF Manifest URLs from resources within Figgy.

I feel that, for these cases, it might be necessary to transmit a HTTP request in order to determine whether or not the IIIF Manifest URL (from the third-party institution) can be resolved.  Otherwise it would need to be handled within the browser before the UV is rendered in the `iframe`.

If this seems reasonable, I would advocate for extending only Orangelight to handle these requests.  Requesting over the HTTP and caching validated IIIF Manifest URLs seemed to introduce some obstacles into maintaining and extending this on https://github.com/pulibrary/marc_liberation (I speak here only as the party responsible for initially introducing this into the code base, not as a critic of the work which took place afterwards).

**Comment by christinach** [comment]
We remove all links from partner records when we index SCSB. We also remove urls from oclc. We move them into 956 field and we don't index it. 
If a link is desired to be indexed they should reach out to the Electronic Resources team they add it in a portfolio and then it will display in the catalog.
