### ISSUE TITLE
Make left sidebar narrower and/or move Available Online to it

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1522]
Particularly when there is lots of text in the title or other main info, the call number and other info about the location of the item is pushed down lower than the See Also section, shifting focus away from the item and towards going elsewhere.

Some options for addressing this:
* Make the left sidebar narrower (freeing up more space for long titles, etc.)
* Move Available Online section to left sidebar (which makes sense since it's right below the thumbnail)
* Move the See Also box down to the top of the Details section to prevent it from being higher than the Copies in Library section

**Comment by hackmastera** [comment]
I don't love these options and I'll enumerate why. But I'm also not super convinced by the argument in this suggestion. Perhaps someone with fresher knowledge of user behavior research could weigh in. But height on page is just one factor of where someone looks. The main column presumably also has more weight than a sidebar.

For example, maybe moving online links to the sidebar makes "copies in the library" more prominent, but maybe it also makes online copies less prominent (by moving it out of the main column), and aren't there lots of users who are well-served by emphasizing the resources that are available online?

Re: narrower sidebar, 1-third / 2-thirds is pretty standard and I worry that other ratios might look "off".

re: moving available online to the left; this removes it from its grouping with "copies in the library"; as 2 different ways to access it makes sense for them to be together.

re: moving "see also" into main section -- I don't really have any argument against that except that it leaves the thumbnail all alone and a bit naked looking.

Would it make sense to increase the size of the thumbnail? That might look nice on its own, but might also give the "see also" section slightly less weight.

**Comment by escowles** [comment]
My concerns about the Copies in the Library section being hidden are addressed by https://github.com/pulibrary/orangelight/issues/1520#issuecomment-448255334.  But I think there is a slightly different issue I wanted to highlight: part of the concern is that the See Also section is very prominent, which seems strange because it's directing users to go find the item somewhere else. See screenshot for a < 1000px view where the See Also box is visible but Copies in the Library is not:
![screen shot 2018-12-18 at 10 26 35 am](https://user-images.githubusercontent.com/856924/50164347-73189000-02b0-11e9-8fbf-beb6ca055192.png)

When there are usage restrictions or other availability issues, I think having the link to WorldCat is great.  But it seems unhelpful for it to be so prominent when the item is available at Princeton or online.

**Comment by jpstroop** [comment]
> Move the See Also box down to the top of the Details

I think it's fine where it is on very wide screens, but maybe it should jump down below *Details* sooner? I think this could be OK with the sticky-menu idea @kevinreiss mentioned, but obviously testing should bear that out. 

I think there might be a more subtle challenge in that there are multiple reasons why a user might want to "See Also", and that might influence how important that menu/feature is to them. Not sure if that's a solvable problem.

**Comment by hackmastera** [comment]
@escowles I agree I also think the see also section is quite prominent. I think making the thumbnail bigger would help this. I also think some subtle style changes to the "see also" box could help. Maybe take away the bg color from the header, or make it slightly smaller to be closer in size to the thumbnail. Interested in @axamei's thoughts.

**Comment by axamei** [comment]
@hackmastera We played around with the size of the thumbnail, but when we increased the size in the Google Books API, fewer book covers were returned. Perhaps someone with more familiarity with the API can take a look at what options we have regarding size.

We should not move around the availability content. Separating the online availability information from the physical availability into the sidebar becomes an accessibility issue, i.e., the meaningful sequence of the information on the page follows no logical order.

Summary of alternatives for show page display:

- Remove the background color from the panel to closely resemble what the sidebar panels look like in production. 
- Add internal navigation to help indicate what content is available to our users. 
- Move some prioritized top fields back to "Details" section.
- Move "See also", "Restrictions", "Other versions", and "Limited excerpts" under "Details".

**Comment by sdellis** [comment]
I'm a bit late to this party, but I have a few thoughts. 

First, I don't necessarily see "white space" as a problem, but I agree that "See also" may have more prominence than it should. I am a little fuzzy on the use case for "See also" but am I correct that this is used more by Librarians than patrons?

Second, I would like to see links/icons that allow quick access to both digitized content or online versions in the thumbnail area. I agree with @axamei that it should also be present in the "Copies In Library" section. In this way, that area could loosely follow the Amazon "Look inside" convention that people may be familiar with.  I would also like to see the table of contents ("Contents") formatted better and display below the thumbnail, since the UV also displays the contents in the left panel. I am aware that the content metadata (505 field) is not always consistent, but it seems manageable for most cases. This would group the item's immediately accessible content in one area.

Internal navigation could be helpful. I'm not sold on [Stanford's approach](https://searchworks.stanford.edu/view/312252), but it's worth exploring.

It would be good to explore the issue with Google API and larger thumbnail requests. I agree that the alignment can seem off with the smaller thumbs.

One final comment on the "Copies in the Library" section. I did not immediately see this as a table "row". I saw three columns that for a minute I thought there were three different items. If there were more copies, perhaps with striping, it would be more obvious. I wonder if this could be made more evident for when we have single copies? 
![screen shot 2018-12-19 at 10 41 47 am](https://user-images.githubusercontent.com/609368/50230748-4c735b80-037b-11e9-851a-ff417fcf77b9.png)
