### ISSUE TITLE
url facet param not being referenced as an array throws an error

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1554]
## Backtrace

    line 55 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: facet_fields_values
    line 88 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: validate_for!
    line 11 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/41345535)

**Comment by tampakis** [comment]
Any url of the form https://catalog.princeton.edu/?f=anything throws an error because the application expects a hash https://catalog.princeton.edu/?f[author_s][]=Princeton+University.+Department+of+African+American+Studies
We don't have any active links to catalog to this invalid url but should have the standard 404 display
