### ISSUE TITLE
Index LibGuides into Catalog?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#1640]
See if there is an API or scrape urls: https://libguides.princeton.edu/

**Comment by tampakis** [comment]
Issues involve libguides being out-of-date, that lots of links in the guide link back to the catalog, the mixed nature of the content (event webpages, group wikis, subject guides)

**Comment by tampakis** [comment]
Integrate into course reserves feature? Since there are libguides for individual courses

**Comment by jpstroop** [comment]
I thought Solr had an analyzer for HTML, but maybe I'm wrong. Based on the feedback I heard yesterday, I suspect that even out-of-date libguides would be helpful as long as they're not blatantly wrong. I wouldn't worry about them being for specific courses, either. 

This _could_ be a feature beyond just indexing--maybe they get bento-ed into the OL results page somehow so that they aren't buried? Or maybe guides just get mapped to certain call number ranges and are suggested when the user looks at a record (maybe they're not indexed at all?)

**Comment by christinach** [comment]
We will discuss this in the Orangelight meeting how the new all search api might be able to fulfill bringing libguides into catalog search results.

**Comment by sandbergja** [comment]
Discussed in today's Orangelight meeting. It's an interesting idea, but we don't have any evidence that users would be interested/would actually use this feature.  We will discuss this with AUX as a future topic to look into.   When/if we get evidence that users would use this, we can open it again.
