### ISSUE TITLE
[Orangelight/production] NoMethodError: undefined method `collect' for "()"@5:Parslet::Slice

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1656]
## Backtrace

    line 16 of [PROJECT_ROOT]/app/models/search_builder.rb: cleanup_boolean_operators
    line 23 of [PROJECT_ROOT]/app/helpers/blacklight_helper.rb: search_results
    line 493 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/43241543)

**Comment by hectorcorrea** [comment]
The culprit is that the query submitted on the request ends with "()" and Blacklight is throwing an exception when trying to parse this query.

The URL in the Honeybadger report is 

```
https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=Philipps+Payson+O%E2%80%99Brien%2C+How+the+War+Was+Won%3A+Air-Sea+Power+and+Allied+Victory+in+World+War+II+%28%29
```

When we decode the `q` parameter we get:

```
Philipps Payson O’Brien, How the War Was Won: Air-Sea Power and Allied Victory in World War II ()
```

Blacklight has some built-in error handling to deal with `Parslet` exceptions but it seems that this exception is not a `Parslet` exception per-se (although it happens in `Parslet`) and Blacklight is just letting the exception bubble all the way to the top.
