### ISSUE TITLE
Check for digital object linked to parent record (773$w)

### ISSUE THREAD

**Issue by escowles** [pulibrary/orangelight#1661]
If a record has a parent record id in 773$w, check to see if it has digital content and display it. Example record: 6910128 (currently ingested as MVW with parent linked to parent record and volume linked to child record)

This will greatly simplify displaying digital content for sammelbands, where there is a parent record for the physical volume, and child records for the parts.  We can ingest the item as a single ScannedResource linked to the parent record, and it will show up in the child objects.

**Comment by escowles** [comment]
Should this be closed? I'm seeing the viewer linked to 6910125 displayed on both 6910125 (host) and 6910128 (volume).

**Comment by tpendragon** [comment]
6910125 is displaying the MVW manifest (you can tell by the ToC), and 6910128 is showing the viewer for just the volume.

One could argue this is correct?

**Comment by escowles** [comment]
Yes, this is a good setup, and the goal for this ticket was to get this behavior. I looked at the records again and now I see that the volume has 6910128 as the source metadata identifier, which is why it's displaying on the child volume.

Going forward, I think we are going to structure things differently and only create a (non-MVW) for ScannedResource for sammelbands, and use structure to represent the volumes/internal structure instead of creating volumes and separate digital objects for each one. So I think we'll need to update the query to see if Figgy has any objects to check the items bib, and also 773$w if that's present.

**Comment by tpendragon** [comment]
Host records are changing a bit in Alma, safe to take off the high priority label?

**Comment by escowles** [comment]
Yes, that makes sense — I've removed the `high-priority` label. This ticket can be prioritized with all the other digital projects work later this year.

**Comment by christinach** [comment]
@tpendragon @escowles can you clarify what we want to display in the host record ? 
https://catalog.princeton.edu/catalog/9969101253506421/
constituent: https://catalog.princeton.edu/catalog/9969101283506421/ 
9969101363506421
9969101413506421

**Comment by tpendragon** [comment]
The proposal here is that https://catalog.princeton.edu/catalog/9969101283506421/ would also show the same viewer that's in https://catalog.princeton.edu/catalog/9969101253506421/ (which has all three volumes.) It would do that by querying Figgy for the host record IDs in addition to the constituent IDs.

This is because in the future there won't be volumes in Figgy for individual volumes in a bound-with, the only link will be from Figgy to the host record.

**Comment by christinach** [comment]
We checked with @kelea99 the host record and a different constituent: https://figgy.princeton.edu/catalog?q=9969101363506421 and the viewers where different. 
I couldn't understand why this constituent https://catalog.princeton.edu/catalog/9969101283506421/ would have a viewer since I couldn't find it in figgy; https://figgy.princeton.edu/catalog?q=9969101283506421 returns no results. 

@kelea99 I found the figgy object id for this '9969101283506421' constituent and  I checked in figgy:  https://figgy.princeton.edu/catalog/42cc0f57-eb6a-4953-9af6-40415d8ddf02 and has source identifier : [9969101283506421](https://catalog.princeton.edu/catalog/9969101283506421/) This is why we see the viewer on the constituent because there is already a scanned manifest in figgy. 
I confirm that it has nothing to do with the host viewer.  

Any ideas why when I search in figgy for '9969101283506421' I get no results??

**Comment by kelea99** [comment]
@kelea99 will talk to DACs in 1/2024

**Comment by christinach** [comment]
@kelea99 any updates on this ticket?

**Comment by kelea99** [comment]
Hi, @christinach ! So, there should not be a viewer in the constituent record. it should only be in the host record, which appears here: https://catalog.princeton.edu/catalog/9969101283506421/

**Comment by christinach** [comment]
Thanks @kelea99 !

**Comment by christinach** [comment]
> Hi, @christinach ! So, there should not be a viewer in the constituent record. it should only be in the host record, which appears here: https://catalog.princeton.edu/catalog/9969101283506421/

The host record is https://catalog.princeton.edu/catalog/9969101253506421/ and it has a viewer. (The record you posted in your comment is the constituent)

The constituent records are : https://catalog.princeton.edu/catalog/9969101283506421, https://catalog.princeton.edu/catalog/9969101363506421, 
https://catalog.princeton.edu/catalog/9969101413506421 and they don't have a viewer.

Can we close this ticket?

**Comment by kelea99** [comment]
What was decided: Volumes with Host and constituent records: The digitized complete volume will only be hooked to the host record.  not constituent records. Closing ticket. Thank you, @christinach !!
