### ISSUE TITLE
Alerts for Saved Searches

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#170]
Allow users to save an arbitrary query and receive email updates at the frequency of their choosing notifying them of new items adding to the system matching that query. This feature might be something that is appropriate for a basic Blacklight Plugin. I think the following options come in to play.
1. User should be able to set their preferred email address for the alert 
2. The alert should come to the user at a frequency of their choosing (monthly, weekly, daily)
3. Some sort of task/queue/mechanism needs to be set up in order to run the alerts.

**Comment by jpstroop** [comment]
It seems like an option on this screen

http://pulsearch-dev.princeton.edu/saved_searches

"Email me when these results change" or something would be the way to go. To get exclusively "new" items, we'd need to get the date that the record was created in voyager into a custom 9xx field, I think. 

@joycebcat does that sound right to you? The date we added the record to Voyager isn't in the MARC already, correct?

**Comment by joycebcat** [comment]
@jpstroop 
There are dates in the V record; there is a mfhd_create_date and a create_date from the bib.  What should go into a new titles section?  Records (bib and mfhd) are created when something is ordered--these can take some time to arrive and a few never do.  We create a 902 field which has a subfield with yyyymmdd in |e.  This indicates material which is newly-cataloged but doesn't cover everything newly-added to the catalog.  The item also has a create date on it.  That would prevent e-resources and things on order from showing up in the new titles section but would include new volumes added to existing objects and also older material as it gets barcoded (not so frequent anymore).  I think the first step is to decide what should be included in such a list ideally, then look at what data elements can be used to achieve that.

**Comment by tampakis** [comment]
@joycebcat the 902 field is a relatively new cataloging practice right? I see it in this [July 2014 record](http://bibdata.princeton.edu/bibliographic/8546312), but not in this [June 2014 record](http://bibdata.princeton.edu/bibliographic/8516312).

I think what would be the easiest and most complete way of setting up these alerts and to come up with a solution to #117 is to take the catalog date based on the bib create date, since we already pull that value daily in bibdata. Maybe we could refine it to only include it when the order actually comes in, but I don't think the current service does that.

**Comment by joycebcat** [comment]
902 has been in use since 1999 but as I mentioned, it doesn't appear on all newly-added records.  What is primarily missing is bulk-loads of e-resources.  There are some other lesser categories which wouldn't get a 902.  I think using a built-in date is the way to go, but we will need some additional filter element depending on what we actually want to include in the new title list.

**Comment by tampakis** [comment]
Since we were planning on using Solr to include this field, it would probably be part of another 9xx MARC field. Do you know of a good 9xx value we could use that doesn't step on another local field?

**Comment by tampakis** [comment]
@jpstroop and I think that we could use the create_date from the bib_master table and and exclude any records that aren't available. We may need to clarify what that means later, but right now we are taking that to mean everything is available if it isn't on order.

**Comment by jpstroop** [comment]
Semantics are "Date Available". Solution: in `959 |a` add the date of the oldest item unless there is an `elf*` holding, in which case use the create date from the bib_master table. Add no date if the item is not available (e.g. on order).

**Comment by tampakis** [comment]
From Sandy: New Acquisitions Alert—ability to set up a regular email of recent acquisitions scoped by location, subject, etc.

**Comment by jpstroop** [comment]
Could we avoid having to run scheduled jobs for (essentially) checking the RSS feed and sending an email by making users more aware of the RSS feature, and if they really need an email suggest they look at any number of third party utilities, such as: https://blogtrottr.com/

**Comment by jpstroop** [comment]
Here's a gem that does RSS to email: https://github.com/agorf/feed2email. It's mean to be a CLI, but maybe we could hook into it somehow?

**Comment by tampakis** [comment]
Closing this issue since saved searches is no longer supported
