### ISSUE TITLE
Use authorization data from graphql when presenting links to digital objects

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#1722]
Handle the authorization data provided via https://github.com/pulibrary/figgy/issues/3206. In support of iiif-auth work.

May require some wireframing to determine the right UI.

**Comment by christinach** [comment]
@hackartisan do we still need this?

**Comment by kevinreiss** [comment]
@tpendragon @hackartisan is this still a use case?

**Comment by tpendragon** [comment]
I honestly don't remember what the use case for this was. I think you can close it? We do some more advanced stuff for displaying content in Pulfalight depending on if someone could login and possibly get access to it, but in Orangelight I think you get a less-pretty-but-still-functional login window ever since we implemented CDL.

**Comment by kevinreiss** [comment]
Ok, thanks. I'll close the issue and if something comes up in the future in this space we can start a new issue.
