### ISSUE TITLE
Call numbers issues because of the load balancer

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1967]
## Backtrace

    line 76 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: block (2 levels) in browse_cn
    line 73 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: times
    line 73 of [PROJECT_ROOT]/lib/orangelight/browse_lists.rb: block in browse_cn

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/54544423)

**Comment by christinach** [comment]
This is a known error we had in the past. One workaround that @tampakis introduced was to have the task running against a specific solr box (lib-solr3 in the past) and not through the load balancer. The problem was that the task was taking to much time to pull the data from solr and nginx was timing out. We also found out that `lib-pulindexer1` was very slow. @kayiwa reprovisioned the box and `lib-pulindexer1` was back on speed. 
Another thing to consider for this error is that an indexing process was triggered at the same to fix the cjk.

**Comment by christinach** [comment]
When the indexing finishes I will trigger this task again to fix the missing call numbers and will close this issue.

**Comment by christinach** [comment]
I checked today the call_numbers_browse_s.sorted file and it seems larger (contains more lines) than the previous one (which was missing 147,000 lines). Pointing to a solr8-box fixed the issue. It is better not to run this task through the Load Balancer. 

This task runs on lib-pulindexer1. Someone can check the call_numbers_browse_s on the /tmp directory.
