### ISSUE TITLE
CDL items should have status "Reserved for Digital Lending", Online section with "View digital content" link, and no request button

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/orangelight#2176]
Use final wireframes from #2171

Implementation notes:

- Likely requires a PR to bibdata's availability endpoint.
- Implementation will be primarily in javascript; "Available Online" area will need to be inserted.
- Request button will need to be removed.

**Comment by kevinreiss** [comment]
Is it possible to add the "Reserved for Digital Lending" status to the availability call? That can be used to make sure the request button doesn't show up.

**Comment by christinach** [comment]
I had a quick call with @mzelesky and opened https://github.com/pulibrary/voyager_helpers/issues/114. I'll open a PR and test it on bibdata-staging. When we first added the patron_group_charged attribute we didn't pull it all the way to the full_mfhd_availability because the need was only to retrieve it in the EligibleItemService using https://bibdata.princeton.edu/bibliographic/7214786/items. Also @mzelesky explained that the https://github.com/pulibrary/voyager_helpers/blob/839acb7db247150fded107989a14680a0cc4d8ce/lib/voyager_helpers/liberator.rb#L214 is used on the search results page not on the record page. Thank you @mzelesky for your valuable input!
