### ISSUE TITLE
ETAS links should not show if an item is charged

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2237]
There is a consensus that if we can we should try and suppress ETAS links for items that move into a charged status in Voyager.

**Comment by hackmastera** [comment]
@kevinreiss is this strictly for a "charged" status? Orangelight has a concept of `checked_out_statuses` should this apply for all of them? 
```
    this.checked_out_statuses = ['Charged', 'Renewed', 'Overdue', 'On hold',
      'In transit', 'In transit on hold', 'In transit discharged', 'At bindery',
      'Remote storage request', 'Hold request', 'Recall request'];
```

**Comment by kevinreiss** [comment]
I think for the purposes of simplicity yes.

**Comment by mzelesky** [comment]
I think all `checked_out_statuses` would apply, yes.

**Comment by carolyncole** [comment]
Here is an example of a checked out item, that is not hiding the link. https://catalog-staging.princeton.edu/catalog/611143

**Comment by kevinreiss** [comment]
When the item still displayed the link it was marked as "On Hold" in the availability lookup. Once it transitioned to "Charged" the link went away. I wonder if this a cases sensitivity issue since the javascript is looking for "On hold" and the availability status from bibdata had "Hold" capitalized.

**Comment by hackmastera** [comment]
Thanks for figuring that out @kevinreiss; made it very easy to put up a fix.
