### ISSUE TITLE
Catalog show page has no call number, but request page does

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2250]
There is no call number on this page:
https://catalog-staging.princeton.edu/catalog/11889186

There is one on this page:
https://catalog-staging.princeton.edu/requests/11889186?mfhd=11543318&source=pulsearch

It seems like there should be either non on both or a call number on both.  One of the systems has a bug.  If the call number is accurate in requests then it should be shown on the catalog.

**Comment by christinach** [comment]
I checked the same record on production and it does have a call number. https://catalog.princeton.edu/catalog/11889186. The reason it doesn't show on staging is because the rake task doesn't run through a cron job on staging. We run it manually when we remember or need to test something. 
The following cron schedule is only for production. 
https://github.com/pulibrary/orangelight/blob/d96191e8ea34357f68644f6736dc29727872bb9b/config/schedule.rb#L27
