### ISSUE TITLE
Availability not populating for all the search results

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2417]
See https://catalog-alma-qa.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=musicals -- results 3, 4, 6, 8, 10, and 14 never populate

**Comment by christinach** [comment]
The records that dont display availability they all have etas location in the api call. https://bibdata-alma-staging.princeton.edu/bibliographic/9929723813506421/availability.json `{"9929723813506421":{"other":{"on_reserve":"N","location":"etas","label":"ETAS","status_label":"Available","cdl":false,"holding_type":"other","id":"other"}}}`
https://catalog-alma-qa.princeton.edu/catalog/9929723813506421

**Comment by christinach** [comment]
I also think that when we ran the index @tpendragon had removed elfs and etas from the bibdata db so they don't get indexed in the holdings1_display. For example this record includes in the holdings1_display only firestone$stacks. `"holdings_1display": "{\"22159277990006421\":{\"location_code\":\"firestone$stacks\",\"location\":\"Firestone Library - Firestone Library Stacks\",\"library\":\"Firestone Library\",\"call_number\":\"PN1995.9.M86 M874 2000\",\"call_number_browse\":\"PN1995.9.M86 M874 2000\",\"items\":[{\"holding_id\":\"22159277990006421\",\"id\":\"23159277970006421\",\"status_at_load\":\"1\",\"barcode\":\"32101039113301\",\"copy_number\":\"1\"}]}}",` 

and not etas which is the temporary location based on the api call `<in_temp_location>true</in_temp_location>
            <temp_library desc="Electronic Access">online</temp_library>
            <temp_location desc="ETAS Non Circulating">etas</temp_location>`

Did we remove displaying availability for temporary locations?

**Comment by christinach** [comment]
Reviewing this issue with @mzelesky 
If an item is in a temp location and it is the only item on a holding then the only AVA returned is for the temp location and it doesn't include a holding_id ($8).
`tag=\"AVA\"><subfield code=\"0\">9929723813506421</subfield><subfield code=\"a\">01PRI_INST</subfield><subfield code=\"b\">online</subfield><subfield code=\"c\">ETAS</subfield><subfield code=\"d\">PN1995.9.M86 M874 2000</subfield><subfield code=\"e\">available</subfield><subfield code=\"f\">1</subfield><subfield code=\"g\">0</subfield><subfield code=\"j\">etas</subfield><subfield code=\"k\">0</subfield><subfield code=\"p\">1</subfield><subfield code=\"q\">Electronic Access</subfield></datafield>`

If there are some items on a holding in a temp location and others in the permanent location then there are 2 AVAs returned
`tag=\"AVA\"><subfield code=\"0\">9930823573506421</subfield><subfield code=\"a\">01PRI_INST</subfield><subfield code=\"b\">online</subfield><subfield code=\"c\">ETAS Non Circ ReCAP</subfield><subfield code=\"d\">DS793 .C48 vol.452</subfield><subfield code=\"e\">available</subfield><subfield code=\"f\">5</subfield><subfield code=\"g\">0</subfield><subfield code=\"j\">etasrcp</subfield><subfield code=\"k\">0</subfield><subfield code=\"p\">1</subfield><subfield code=\"q\">Electronic Access</subfield></datafield><datafield ind1=\" \" ind2=\" \" tag=\"AVA\"><subfield code=\"0\">9930823573506421</subfield><subfield code=\"8\">22100002150006421</subfield><subfield code=\"a\">01PRI_INST</subfield><subfield code=\"b\">recap</subfield><subfield code=\"c\">Remote Storage</subfield><subfield code=\"d\">DS793 .C48 vol.452</subfield><subfield code=\"e\">available</subfield><subfield code=\"f\">1</subfield><subfield code=\"g\">0</subfield><subfield code=\"j\">pa</subfield><subfield code=\"k\">0</subfield><subfield code=\"p\">2</subfield><subfield code=\"q\">ReCAP</subfield><subfield code=\"t\">Pt.1-pt.6</subfield></datafield>`

The current approach we have to show availability in the show and search results is to show the calculated availability at the holding level based on the AVA fields. If items are in a temporary location there is not holding id in the AVA. So we cannot have a 'Request' button next to the holding.  

To make this work in Alma we would use a work order like we do for 'CDL' instead of a temporary location.

**Comment by hackartisan** [comment]
We could modify bibdata to call the holdings/ALL/items endpoint where the holding id is missing, or maybe when the holding id is missing and it's not ETAS.

Note that the end state is that ETAS is not a temp location, regardless.

The items would all have to be grouped by holding id and synthesized into the response.

The fact that we have so many ETAS items means there are millions of items with temporary locations. Without ETAS it might only be reserve items, maybe new book shelves, things that are temporarily in "the Annex".

Alternately, we use the index to store ETAS status.

**Comment by christinach** [comment]
We also asked in basecamp to see what options we have moving forward https://3.basecamp.com/3765443/buckets/20717908/messages/3704833560

**Comment by hackartisan** [comment]
We think this was fixed, but need to confirm that an item in a temporary location is coming through with the correct availability.

**Comment by hectorcorrea** [comment]
This is indeed broken for issues with temporary locations. Closing this issue since the original problem has been addressed, and opening a new issue (#2524) for the temporary locations problem.
