### ISSUE TITLE
Define database migration plan

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2450]
Implementation tasks:
- [x] Add new browse tables for use by alma infrastructure
- [x] Ensure bookmark links will still work
- [x] Hook catalog production DB to catalog-alma production.

Additional tasks:
- [x] provide info for a "what will happen" website
  - note that e-resources (e-journals and some e-books) are not going to have mappable IDs and so a link would not be redirected)

Background:
- Initially we considered pointing to the same database we have been using in production. However, the browse lists cannot be shared between the 2 sites, as indicated in comments below.
- Then we decided to migrate the database, but this is non-trivial due to its size.
- Finally we decided to add additional tables for the alma infrastructure to use.

**Comment by christinach** [comment]
We would have to disable the cron jobs first.

**Comment by christinach** [comment]
maybe batter not deploy them on the alma_qa worker boxes

**Comment by tpendragon** [comment]
I'm wondering about an alternative plan here:

What if we made another set of browse list tables, for alma? If OL is configured to use Alma it uses those, otherwise it uses the old ones.

**Comment by christinach** [comment]
@tpendragon my thought was to create new browse lists tables to close this issue https://github.com/pulibrary/bibdata/issues/1362. Now that we have a separate alma branch I dont think there is a problem to have the cron jobs running on the new pul indexer boxes https://github.com/pulibrary/orangelight/blob/af08d2c343e81c7be89c5ac91d65f5305bce72db/config/schedule.rb.

The migration should be considered for other tables. For example for bookmarks.

**Comment by hackartisan** [comment]
Will doubling the browse lists be a database size issue? Look on postgres and see how big the tables are.

**Comment by tpendragon** [comment]
I've done this in QA.  A couple things:

1. In catalog-alma-qa there's no way to login to see your bookmarks, except via the link that appears in the "temporary bookmarks" piece. The page you get at that point has barcode login - is that still a thing?
2. The bookmark count is right, but after clicking you get no bookmarks. This is because it does a solr search on all the stored IDs, which are now wrong. I think we can patch the barcode controller to replace all those IDs with alma equivalents and this feature should work fine.
3. Search history doesn't migrate. This is because searches aren't attaching to users, it's just displaying the searches from your session. I don't know if this is a bug or I'm misunderstanding the feature or what. Are there still "saved searches"? In any case, it might be that these are just lost.

**Comment by hackartisan** [comment]
There's a link to log in on both the bookmarks page and the saved searches page.

I think searches from the session should become saved searches if you log in.

**Comment by tpendragon** [comment]
Nah I think saved searches have been broken since 2019:

```
#<Search id: 76058995, query_params: {"utf8"=>"✓", "f1"=>"all_fields", "op2"=>"AND", "f2"=>"author", "op3"=>"AND", "f3"=>"title", "f_inclusive"=>{"advanced_location_s"=>["rcpph"]}, "range"=>{"pub_date_start_sort"=>{"begin"=>"", "end"=>""}}, "sort"=>"score desc, pub_date_start_sort desc, title_sort asc", "search_field"=>"advanced", "controller"=>"catalog", "action"=>"index"}, user_id: 3, user_type: "User", created_at: "2019-07-16 20:06:58", updated_at: "2019-07-18 17:39:41">
```

That's the most recent saved search attached to a user.

**Comment by tpendragon** [comment]
I don't have the background info to know which resources are gone so I don't really feel qualified to write up documentation about it. I'm gonna pull myself off this ticket and put it back in ready.

**Comment by hackartisan** [comment]
I added some language to https://docs.google.com/document/d/1JykBLg5w7P6INQshtdzMwBCGbIDjN11gTuHxjRYndas/edit#
