### ISSUE TITLE
Digitization Requests should still be viewable in orangelight instead of forcing the user to go to Illiad

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/orangelight#2491]
We are removing the Account information coming from Alma from the account page, but there is still a set of information from illiad on the page.  We would like the user to not have to go to yet another system and would like for the account page to be refactored to show a link to alma account and the digitization requests.

**Comment by hackartisan** [comment]
This seems like the time to consider a permanent alma branch on orangelight, rather than doing this with the use_alma switch.

I am thinking a new link under "Your account" called "Digitization requests" that will lead to basically the old account page but without any of the voyager stuff. Sound right?
