### ISSUE TITLE
Stackmap not working for Architecture

### ISSUE THREAD

**Issue by pmgreen** [pulibrary/orangelight#2608]
Architecture locations test successfully within Stackmap itself, but seem to be failing from the catalog. Example:

From Stackmap test: https://princeton.stackmap.com/view/?callno=NA1080.R85%20B54%202019&location=arch$stacks&library=Architecture%20Library

From the catalog: https://catalog.princeton.edu/catalog/99118878653506421/stackmap?loc=arch$stacks&cn=NA1080.R85%20B54%202019

Locations from other libraries appear to be working.

**Comment by christinach** [comment]
Engineering Library has the same problem https://catalog.princeton.edu/catalog/99123831363506421

**Comment by christinach** [comment]
We checked with @pmgreen and engineer$nb is not mapped in the stackmap. @pmgreen will discuss further with @kevinreiss about unmapped locations in stackmap.

**Comment by christinach** [comment]
Confirm with @kevinreiss that the alma locations are updated in the stackmap.

**Comment by hectorcorrea** [comment]
It looks like Stackmap has the right data, at least it seems to find the call number "NA1080.R85 B54 2019" for MMS_ID [99118878653506421](https://catalog.princeton.edu/catalog/99118878653506421) if I manually test it on the app

![arch_stacks](https://user-images.githubusercontent.com/568286/133675852-3b2e2186-4bf6-44b0-a642-5652d058f284.png)

**Comment by hectorcorrea** [comment]
In Orangelight, the page to [view the StackMap](https://catalog.princeton.edu/catalog/99118878653506421/stackmap?loc=arch$stacks&cn=NA1080.R85%20B54%202019) calls the [Firestone Locator](https://github.com/pulibrary/firestone_locator) and embeds the result via an `iframe` with `src` "https://locator-prod.princeton.edu/index.php?loc=arch$stacks&amp;id=99118878653506421&amp;embed=true"

Notice that Orangelight only passes a location code (e.g. "arch$stacks") and an MMS_ID (e.g. "99118878653506421") to the Locator (see code https://github.com/pulibrary/orangelight/blob/main/app/services/stackmap_service.rb#L48) and this is good enough for the StackMap to work in most cases. 

I suspect internally the Locator fetches the item and gets the call number (since we do not pass it down) and then the Locator gets the map from StackMap. 

This leads me to believe that error is either in StackMap or in the Locator. However since the StackMap finds the map if we give it the call number (see comment above) I am thinking that the issue is in the Locator application but I will need to confirm this with Kevin or Carolyn.

I do not know much (anything really) about the Locator application, but I noticed that it makes a call to "http://library.princeton.edu/searchit/record/$id.json" and I don't think those resolve at all. They are redirected to library.princeton.edu/searchit/record/$id.json and that URL always gives me an error "No route found for GET" -- but this might not be the code that gets executed.

**Comment by kevinreiss** [comment]
The data here needs updating: https://github.com/pulibrary/orangelight/blob/main/app/services/stackmap_service.rb#L76

"architecture" should just be "arch"
"engineering" should just be "engineer"

this is causing this conditional to give you the wrong iframe link https://github.com/pulibrary/orangelight/blob/main/app/services/stackmap_service.rb#L76

**Comment by kevinreiss** [comment]
Also, more locations to update in this method

https://github.com/pulibrary/orangelight/blob/804582abf64e980fb589ea05e55ac1dae8ff6280/app/services/stackmap_service.rb#L80-L87

We need to add the "library$" prefix for each of these four locations.

**Comment by kevinreiss** [comment]
and here as well https://github.com/pulibrary/orangelight/blob/804582abf64e980fb589ea05e55ac1dae8ff6280/app/services/stackmap_service.rb#L80-L87.

**Comment by hectorcorrea** [comment]
Thanks @kevinreiss
