### ISSUE TITLE
Online Links Display Full URL as title text

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2620]
Previously when an online URL had no label provided we would truncate the link title text to just the hostname rather than spit out the full URL which is often long and ugly.

<img width="767" alt="Screen Shot 2021-08-04 at 12 50 34 PM" src="https://user-images.githubusercontent.com/278825/128230253-9ba038a7-f1b8-4873-9447-8c3425a09315.png">

**Comment by hackartisan** [comment]
@kevinreiss so what should the link title be?

**Comment by christinach** [comment]
I'm looking into it.

**Comment by christinach** [comment]
This record specifically has in alma an inactive electronic portfolio. This inactive url it does not resolve to anything and it doesn't have a title because it is inactive. It should not be indexed in the electronic portfolio. One option would be not to include inactive portfolios in the publishing job (I don't know if this can be configured in alma. @mzelesky ) and the second option which we should implement asap is not to index electronic portfolio if 951 subfield $a has an 'inactive status'. I will open an issue for this in bibdata. Unfortunately there are a lot of records like this one with inactive portfolios and a lot of not so nice urls in the search results. 
another example:
record https://catalog.princeton.edu/catalog/99123430173506421 shows that it has in alma an inactive electronic.

**Comment by christinach** [comment]
closing in favor of https://github.com/pulibrary/bibdata/issues/1576
