### ISSUE TITLE
Error in rake browse:call_numbers

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2639]
[Orangelight] NoMethodError: undefined method `error' for nil:NilClass

## Backtrace

    line 81 of [PROJECT_ROOT]/lib/orangelight/browse_lists/call_number_csv.rb: block in solr_cursor_page_body
    line 76 of [PROJECT_ROOT]/lib/orangelight/browse_lists/call_number_csv.rb: loop
    line 76 of [PROJECT_ROOT]/lib/orangelight/browse_lists/call_number_csv.rb: solr_cursor_page_body

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/80786210)

**Comment by hectorcorrea** [comment]
The stack trace points to the `Rails.logger.error` call in https://github.com/pulibrary/orangelight/blob/main/lib/orangelight/browse_lists/call_number_csv.rb#L72-L86 

I am pretty sure this is because the Rake task is running without loading Rails. We could either log the error to the console (e.g. with good old `puts`) or perhaps update the rake task to load Rails by adding `:environment` to the definition https://github.com/pulibrary/orangelight/blob/main/lib/tasks/browse.rake#L28-L32 to read

```
desc 'Pull data for call numbers browse'
  task :call_numbers :environment do
    _sql_command, facet_request, conn = BrowseLists.connection
    BrowseLists::CallNumberCSV.new(facet_request, conn).write
  end
```
