### ISSUE TITLE
Display issue of online holdings

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2668]
@tventimi reported:
On 08/17/2021 he loaded a batch of records for an electronic collection:
https://catalog.princeton.edu/?f%5Baccess_facet%5D%5B%5D=Online&f1=in_series&q1=%E4%B8%AD%E5%9C%8B%E8%97%9D%E8%A1%93%E6%96%87%E7%8D%BB%E5%8F%A2%E5%88%8A.&search_field=advanced

Although these appear in Blacklight now, they appear in search results with
"No holdings available for this record".  The same is true for the record
for the electronic collection itself.

https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=left_anchor&q=+%E4%B8%AD%E8%8F%AF%E7%B6%93%E5%85%B8%E5%8F%A4%E7%B1%8D%E5%BA%AB.+

However, this is not true for all records in this set.  For example, this
record was also loaded as part of the same batch but does show electronic
holdings:

https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=left_anchor&q=+%E4%B8%A4%E4%BA%AC%E6%96%B0%E8%AE%B0%E8%BE%91%E6%A0%A1+%2F+%5B%E5%94%90%5D%E9%9F%A6%E8%BF%B0%E6%92%B0+%3B+%E8%BE%9B%E5%BE%B7%E5%8B%87%E8%BE%91%E6%A0%A1.+

It looks like a display issue in the search results page for online records.

**Comment by hectorcorrea** [comment]
Record `99101494203506421` (Zhonghua jing dian gu ji ku) has no AVA/AVE data from Alma but there is one `856` which is why it shows Available Online in the Show page, but evidently we are not taking this into account in the Search page and therefore it shows "No holdings available for this record" in the Search results.

On the other hand, record `99125378800006421` (Liang jing xin ji ji jiao) has information in the AVA/AVE fields from Alma and also it has two `856` fields. The search results for this record displays Online, very likely because it picks up the information from the AVA/AVE fields.

**Comment by christinach** [comment]
99125378800006421 displays online because of the "electronic_access_1display": "{\"http://publish.ancientbooks.cn/docShuju/platformBookDetails.jspx?docbookid=ZHB440000260&libId=6\":[\"兩京新記輯校\"],\"http://publish.ancientbooks.cn/docShuju/platformBookDetails.jspx?docbookid=ZHB440000261&libId=6\":[\"大業雜記輯校\"]}" which is from 856.
