### ISSUE TITLE
Rare Books and Copy Number Examples

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#278]
Here are two bibliographic IDs where copy notation matters:

616086 (Copy Two)
2478499 (Copy Five)

We might want to add these to the test data set for future development. What can we do to make the request of these with proper item level information in context. If you look up the bib IDs in current systems we don't do too well.

**Comment by tampakis** [comment]
Item sequence is also important for multi-volume works:
http://bibdata.princeton.edu/bibliographic/2002206/items

They all have the same location and there is no way to distinguish them in BL currently: http://pulsearch-dev.princeton.edu/catalog/2002206

Voyager: http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=2002206

**Comment by kevinreiss** [comment]
@tampakis If you need some test records that have many holdings at the same location these Bib IDs are good examples.

**Comment by mzelesky** [comment]
What about collapsing the items in the Copies in Library section to one box per unique location? Then, either just show the 866 $a in the Holding info area or also in the sidebar, and have a line that says which items currently have a status that makes them unavailable? For ones where one item is checked out from a holdings with multiple items, then have the request button appear beneath the 'Where to Find It' button'. If there are multiple copies, have a line that says which copy is unavailable instead of a separate box.

For the things that have to be requested as a matter of course (Rare books, other bibs with empty holdings), you could always show the copy number in the Copies in Library area and the Holding info area (852 $t).
