### ISSUE TITLE
Don't Display Labels of Empty values in the holdings display section

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#2917]
See the issue at the root of this in https://github.com/pulibrary/bibdata/issues/1833

**Comment by sandbergja** [comment]
This issue seems to be specific to our checks within the holdings display section.  When I create solr documents with empty fields and load them in as fixtures, Blacklight is smart enough not to display the fields.  However, when it comes to arrays within the holdings_1display JSON, it looks like our custom check was not checking whether or not they were empty.
