### ISSUE TITLE
Move covers to left in search results?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#307]
When they're at the right, they look a little awkward with extra-long titles:
![screenshot from 2015-10-19 08 41 00](https://cloud.githubusercontent.com/assets/999701/10578022/77a0503e-763d-11e5-985f-62a59ea79c23.png)

**Comment by jpstroop** [comment]
Alternative to #291

**Comment by kevinreiss** [comment]
:-1: To this suggestion. Since we can't reliably expect to have a cover for every title I think we should keep the area that is going to draw the user's eye first focused on the text of the title. The words in the title are what users are mostly to care about and use to scan the results list. Having a preview image on the left is certainly a common pattern in e-commerce sites with facets, but I'm not sure it is the right pattern for our system and data. Most of those systems have a strong level of control of the images they put up which we can't really have here.

**Comment by jpstroop** [comment]
I'm not saying next to the title, I'm saying beneath it, next to the creator & publication info, i.e.:
![screenshot from 2015-10-19 08 41 00](https://cloud.githubusercontent.com/assets/999701/10578540/cc5a541e-7640-11e5-892c-aed5416b0cec.png)

**Comment by kevinreiss** [comment]
I think we should go with the suggestion in #291.

**Comment by tampakis** [comment]
I'd prefer #291 because I think it will minimize the vertical space for each record. Currently the publication info and cover are in the same row. This forces that section to be at least as tall as the cover. In the screenshot above this makes the record take up more space (notice the larger amount of whitespace on the left below the record info). Moving the cover up to be directly below the bookmark option would save space on the page.

**Comment by tampakis** [comment]
This screenshot demonstrates the extra vertical space a bit better:
![cover_whitespace](https://cloud.githubusercontent.com/assets/4650153/10580958/398bc97a-764e-11e5-9b3d-9c9dd3b8387e.png)
