### ISSUE TITLE
Provide Record Responses in jsonld

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3072]
Allow the catalog show page controller to respond with jsonld. Initial use case is to allow figgy to consumer the metadata of records in this form when needed. See current bibdata implementation of a jsonld response for an example (ex: https://bibdata.princeton.edu/bibliographic/99108564513506421/jsonld). 

See for motivation and the context. 
https://github.com/pulibrary/figgy/issues/5229
https://github.com/pulibrary/figgy/pull/5230

Bibdata's current implementation of this controller is at: https://github.com/pulibrary/bibdata/blob/main/app/controllers/bibliographic_controller.rb#L118-L122. A version of this class https://github.com/pulibrary/bibdata/blob/e92ba310e4cc859a8b40494eee018f5e06156eb2/app/models/jsonld_record.rb could be used to package up the catalog's JSON documents into jsonld.

**Comment by maxkadel** [comment]
I feel like I'm making fairly good progress on this by hewing pretty closely to the bibdata code. One place I'm confused right now is [local_identifier](https://github.com/pulibrary/bibdata/blob/e92ba310e4cc859a8b40494eee018f5e06156eb2/app/models/jsonld_record.rb#L139). 

From my reading of the code, it looks like it's 
- only displaying cicognara numbers 
  - This is especially confusing because I don't think those identifiers are local?
- local_identifier doesn't seem to be included in https://bibdata.princeton.edu/context.json, which I would expect.

In addition, I can't seem to find any examples of works with cicognara numbers in the catalog, although that may just be because I don't know how to search for them correctly.

**Comment by maxkadel** [comment]
@tpendragon - the above may be a question for you?
