### ISSUE TITLE
Determine why the location code sometimes gets passed as a hash

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3114]
This ticket is broken off from https://github.com/pulibrary/orangelight/issues/2942 -- we have a fix to handle this Hash case, but haven't yet determined the underlying issue that causes us to receive Hashes here in the first place.

**Expected behavior**

The `render_location_code` method only gets Arrays or Strings passed to it.

**Actual behavior**

Hashes are also getting passed to it

**Steps to replicate**

We were unable to determine how to replicate this in the UI.  We suspect that it may have to do with the advanced search.

**Impact of this bug**

More inconsistency for devs to have to work with.  It also means [we need extra code](https://github.com/pulibrary/orangelight/pull/3113) to handle cases when Hashes are getting passed to this method.

**Honeybadger link and code snippet, if applicable**

https://app.honeybadger.io/projects/54399/faults/85156024 -- note that this is no longer erroring due to https://github.com/pulibrary/orangelight/pull/3113, but we haven't yet diagnosed the underlying issue (which is what this ticket is about).

```

NoMethodError: undefined method `to_sym' for ["0", "Mendel Music Library"]:Array Did you mean? to_s to_set

application_helper.rb 389 block in render_location_code(...)
[PROJECT_ROOT]/app/helpers/application_helper.rb:389:in `block in render_location_code'
  def render_location_code(value)
    values = Array(value).map do |loc|
      location = Bibdata.holding_locations[loc.to_sym]
      location.nil? ? loc : "#{loc}: #{location_full_display(location)}"
    end
```

**Comment by maxkadel** [comment]
Examples of urls that have come in with this error are:

* https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f%5Baccess_facet%5D%5B0%5D=Online&f1=all_fields&f2=author&f3=title&op2=AND&op3=AND&q1=Tchaikovsky&q2&q3&range%5Bpub_date_start_sort%5D%5Bbegin%5D&range%5Bpub_date_start_sort%5D%5Bend%5D&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&f_inclusive%5Bformat%5D%5B0%5D=Audio&f_inclusive%5Badvanced_location_s%5D%5B0%5D=Mendel+Music+Library&f_inclusive%5Badvanced_location_s%5D%5B1%5D=elf1&commit=Search
* https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&f1=all_fields&f2=author&f3=title&op2=AND&op3=AND&q1=Cello+Suite+No.+3+in+C+Major%2C+BWV+1009&q2=bach&q3&range%5Bpub_date_start_sort%5D%5Bbegin%5D&range%5Bpub_date_start_sort%5D%5Bend%5D&search_field=advanced&sort=score+desc%2C+pub_date_start_sort+desc%2C+title_sort+asc&f_inclusive%5Bformat%5D%5B0%5D=Audio&f_inclusive%5Badvanced_location_s%5D%5B0%5D=Mendel+Music+Library&f_inclusive%5Badvanced_location_s%5D%5B1%5D=Online&commit=Search

Note particularly the sections:
* `advanced_location_s%5D%5B0%5D=Mendel+Music+Library&f_inclusive%5Badvanced_location_s%5D%5B1%5D=elf1`
* `advanced_location_s%5D%5B0%5D=Mendel+Music+Library&f_inclusive%5Badvanced_location_s%5D%5B1%5D=Online`

We don't know how these sections were built via the UI, but it's these constructions that are leading to getting a hash rather than a string or array.

**Comment by rladdusaw** [comment]
These request were from Facebook's bot looking for an outdated location code of elf1. Closing the ticket.
