### ISSUE TITLE
Remove campus_authorized feature

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3161]
From @kevinreiss: We used to have a list of the net IDs of folks allowed on campus on various points in the pandemic and restricted services just to that list.

This feature is no longer used, so let's remove it from the code.

Sister issue in bibdata: https://github.com/pulibrary/bibdata/issues/1972

**Comment by sandbergja** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/orangelight/3161?planning-poker) with Zenhub @christinach @maxkadel @regineheberlein @rladdusaw

**Comment by christinach** [comment]
needs some more work. I reverted the pr and merged in main.

**Comment by christinach** [comment]
I reopened the ticket because after deploying to qa and staging I noticed that when the user is prompted to login and submit a request the UI has the message  'You must register with the Library before you can request materials. Please go to Firestone Circulation for assistance. Thank you.' 
The message comes from ‘I18n.t(“requests.account.cas_user_no_barcode_msg”)’.
