### ISSUE TITLE
Catalog JSON-LD sometimes has a blank "lang" tag

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#3181]
### Expected behavior

If there's no language for a title, it should just be the string. See https://bibdata.princeton.edu/bibliographic/9996490803506421/jsonld

### Actual behavior

A long blank lang tag shows up. See https://catalog.princeton.edu/catalog/9996490803506421.jsonld

```json
{
  "title": [
    {
      "@value": "Syria 100K Vector Dataset",
      "@language": "   "
    }
  ]
}
```

### Impact of this bug

We can't migrate over to using the catalog for JSON-LD fetching in Figgy until this is done.

**Comment by tpendragon** [comment]
https://catalog.princeton.edu/catalog/9996371533506421.jsonld is another example.

**Comment by maxkadel** [comment]
Hrm, I think maybe there are two issues

* That a blank language tag is being indexed to Solr (see https://catalog.princeton.edu/catalog/9996490803506421/raw - currently includes `"language_code_s":["   "]`
* That this is being passed on to the jsonld. 

If the first weren't happening, we wouldn't have to worry about the second, but so that the Figgy work isn't blocked by a full reindex, I'm thinking I'll start with fixing the jsonld code in Orangelight, and the indexing work can be done under https://github.com/pulibrary/bibdata/issues/1986

**Comment by christinach** [comment]
I think you can use a new language field we introduced a while ago ''language_iana_s" . It is used in the html lang attribute in Orangelight. If there is no value it will not get indexed. 
https://github.com/pulibrary/bibdata/blob/7c3e63c479ac2f9c8a59b53cfdbe878763ecf5bf/marc_to_solr/lib/traject_config.rb#L744
