### ISSUE TITLE
Holdings Are Displayed out of Sequence on Show Page

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#327]
In the traditional OPAC http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=3256177 holdings are displayed in alphabetic order. 

In PULSearch we don't sort them, see the holdings info field display at http://pulsearch-dev.princeton.edu/catalog/3256177

**Comment by jpstroop** [comment]
Can we do in MARCLiberation? Or do we have to do here?

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by kevinreiss** [comment]
Maybe, right now it gets normalized for the inline display on the show page (the Holdings Info section). I decided to move away from using Umlaut as the primary holdings in favor of a something promises better performance. To that end I'm trying to take the information stored in the solr doc and overlay it with item/location data from bibdata on top of it to produce something to display for request/detailed status information about the items attached to holdings. 

In the interest in performance I was actually thinking we might want to load more information from the Holdings record (holding record ID, Summary Holdings Statements) into the index. The staff/power users are used to seeing this information on page load from Oracle directly and any web service call is going to lag behind that. With that in the index we can reliably display all relevant holdings information on page load and progressively enhance it with basic availability/detailed request information.

**Comment by kevinreiss** [comment]
Also one other quirk that has been a bit troublesome is our common practice of creating multiple holdings at the same shelf location for different individual items. Consider the example record here:

There are five explicit holdings http://bibdata.princeton.edu/bibliographic/3256177/holdings (3 for location code "f"). In our items API  we have collapsed the three "f" locations together http://bibdata.princeton.edu/bibliographic/3256177/items.

**Comment by tampakis** [comment]
This issue was brought up at the meeting today. It was suggested to sort the locations alphabetically with recap appearing last. It could happen at any level, but the safest way of ensuring the sort order would be to place the code in Orangelight. That way, no matter how the holdings hash was indexed (it currently is ordered by holding id, the order the 852s appear), Orangelight can reorder the hash to display however we'd like. If we changed the traject config to set a particular order for the hash, we'd need to do a full reindex (not that big a deal). I don't think it's a good idea doing this in MARCLiberation. We'd have to do another full dump (map the location codes to location names and reorder the 852 elements of each MARC object) of the Voyager DB and index the new set for the changes to take effect.

**Comment by kevinreiss** [comment]
@tampakis I think we can close this one?

**Comment by tampakis** [comment]
No we need to still look at this - I think we discussed a sort order that puts Firestone first, then branch libraries, than off-site locations

**Comment by tampakis** [comment]
This came up again at the staff training. This should be made more consistent soon.

**Comment by tampakis** [comment]
Should be fairly high priority
