### ISSUE TITLE
Submit Alma constituent record metadata with Aeon Requests

### ISSUE THREAD

**Issue by doncat** [pulibrary/orangelight#3273]
TN 354603 provide an example.  A user requests a specific constituent title.  Only host data get passed to Aeon.  Staff need a way to identify the individual item within the host that is being requested.  Pulling the _Item..._ descriptive fields from the constituent, and putting its MMS ID in ReferenceNumber would solve the problem.  It would also parallel EAD component IDs in that field.  Location, CallNumber and ItemNumber (barcode) should continue to come from the host holdings and item, of course.
As a by-product, this change would help with use statistics.

**Comment by christinach** [comment]
Example records that we could look at: 
Host record: https://catalog.princeton.edu/catalog/99125086293506421/staff_view

Constituent record: https://catalog.princeton.edu/catalog/9935069203506421/staff_view

**Comment by christinach** [comment]
@doncat which are the descriptive fields `Pulling the Item... descriptive fields from the constituent,`?

**Comment by doncat** [comment]
These are the Aeon fields:
ItemAuthor, ItemTitle, ItemSubTitle, ItemDate, ItemEdition, ItemVolume, ItemIssue, ItemPages, ItemISxN, ItemCitation, ItemNumber.
Some are kind of implausible!
ReferenceNumber (MMS ID) would be highly useful.

**Comment by doncat** [comment]
Any news on this?  I've had renewed enquiries from the curatorial staff.  Apparently it's a sore point for them.

**Comment by kevinreiss** [comment]
This is a fairly challenging update through I understand why it would help to have the constituent metadata passed over rather than the host record. We will still need to allow the request code to pass over any item level information that resides with the parent record. In our current backlog I do not think we will have time to take substantial look at this until March given other commitments for the upcoming month.

**Comment by doncat** [comment]
April now.  Any prospect of looking more closely?

**Comment by doncat** [comment]
Hello again.  Almost not April any more.  Is there any chance of progress on this matter?
Attaching note from a faculty member, a heavy user of the Jacques Derrida library as further illustration of the problem.
[Re_ Visitor_ the former Ambassador of France to the US.pdf](https://github.com/pulibrary/orangelight/files/11334019/Re_.Visitor_.the.former.Ambassador.of.France.to.the.US.pdf)

**Comment by kevinreiss** [comment]
Hello we discussed this at our weekly check-in for OL issues today. There is a prospect to bring bibliographic level data for the constituent records into the Aeon request.  

So I think we could extract following fields reliably: ItemAuthor, ItemTitle, ItemSubTitle, ItemDate, ItemEdition, ItemISxN, ReferenceNumber. 

I'm not sure how we'd extract the other data from a constituent record the values for ItemVolume, ItemIssue, ItemPages, ItemCitation, ItemNumber since those are at the holding or item level data which only exist under a host record.

**Comment by kevinreiss** [comment]
Possible Implementation:

Constituent records like  99122598533506421 have a a data attribute attached to the id main content element:

data-host-id='["99125092613506421"]'

Currently we use this value as the mms ID to utilize when making an availability call to get the holding and item availability status of the host record from Alma. We could also use this to possible create a hash of constituent bibliographic level parameters taken from the solr document to pass over to the request form that can be used to override values from the host record that would otherwise be submitted to another system like Aeon.

**Comment by doncat** [comment]
Looks very promising!
ItemAuthor, ItemTitle, ItemSubTitle, ItemDate, ItemEdition, ItemISxN, ReferenceNumber.
Those are the key "Item ... " fields to map from the constituent.  (All but one.)  ItemVolume, ItemIssue, and ItemPages can be disregarded.  ItemNumber comes from the host.
**In addition**, map constituent 773 $$g to ItemInfo 3.  It's the folder number.  In this way the Alma transactions will be sort of compatible with some of the EAD transactions.  Anyway, folder is key physical identifier.
Fields continuing to come from the host: CallNumber, Location, ItemNumber.

**Comment by kevinreiss** [comment]
Check both bound-with titles and regular Aeon records.

**Comment by sandbergja** [comment]
closed by #3559

**Comment by hmurusmith** [comment]
Hi @sandbergja! I wanted to follow up on one of the aspects of this earlier closed issue: the mapping of 773 $g to ItemInfo 3. I understand from Public Services that this mapping doesn't seem to be consistently working for requests. And as Don mentioned in his 04/28/2023 comment, it is a key physical identifier that allows Public Services to locate the requested item when it is a constituent. 
Here is an example record: https://catalog.princeton.edu/catalog/99125488809906421 
The 773 $g contains the folder information, which helps locate the item in the box B-000523 (which has 35 foldered items).
Let me know if there is any information I could provide to help explore this further!
