### ISSUE TITLE
Can't download MARC file for record

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3441]
### Expected behavior
The marc file should start downloading

### Actual behavior
The marc file is not downloaded and there is an error screen

### Steps to replicate
visit
https://catalog.princeton.edu/catalog/9934215263506421.marc

### Impact of this bug
E.g. "I can't work until this is fixed" or "I have a workaround"

### Honeybadger link and code snippet, if applicable
https://app.honeybadger.io/projects/54399/faults/94134534
```
marc.rb  44  export_as_marc(...)
[PROJECT_ROOT]/app/models/concerns/blacklight/solr/document/marc.rb:44:in `export_as_marc'

def export_as_marc
--
43 | return '' unless to_marc
44 | super
45 | end

```

### Implementation notes, if any
The record has an extremely long contents field. Possible source of error.

**Comment by mzelesky** [comment]
Extremely long contents fields cause many other problems as well. This doesn't impact the ticket, but I am planning on sweeping through all records periodically to locate fields that are longer than 9,999 bytes.

The byte limit for an individual field in the MARC standard is 9,999 bytes. The byte limit for a record is 99,999 bytes.

There is an option in the ruby-marc gem to allow oversized records, but I don't know if that would really solve this (since it would result in an invalid MARC file).

Perhaps you could check the record before serving it up to see if the record is too large to export in binary format?

This is code I use to find problems like this:

```
def record_size?(record)
    total_size = 0
    total_size += record.leader.bytesize if record.leader
    record.fields.each do |field|
      total_size += 1 # field separator character
      total_size += field.tag.bytesize
      if field.class == MARC::ControlField
        total_size += field.value.bytesize
      else
        field.subfields.each do |subfield|
          total_size += subfield.code.bytesize
          total_size += subfield.value.bytesize
          total_size += 1 # subfield separator character
        end
      end
    end
    total_size > 99999
  end

  def field_size?(record)
    return true if record.leader.bytesize != 24

    record.fields.each do |field|
      if field.class == MARC::ControlField
        return true if field.value.bytesize > 9999

      else
        total_size = 0
        field.subfields.each do |subfield|
          total_size += subfield.code.bytesize
          total_size += 1 # subfield separator character
          total_size += subfield.value.bytesize
        end
        return true if total_size > 9999

      end
    end
    false
  end
```

**Comment by christinach** [comment]
very rare. a few records that this could be a problem.
