### ISSUE TITLE
MapSet records have a viewer per sheet

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#3450]
### Expected behavior
A multi-page MapSet displays in as a multivolume work in a single viewer

### Actual behavior
Each page is rendered in a new viewer.
https://catalog.princeton.edu/catalog/9968107933506421

### Steps to replicate
Go to link above

### Impact of this bug
Looks very bad on MapSet records. Probably hinders page load performance and the ability of users to find what they are looking for.

### Implementation notes, if any

@tpendragon mentioned that there were recent updates to the GraphQL queries made to Figgy to improve performance on some records and these changes are causing this issue.

https://github.com/pulibrary/orangelight/issues/3285

**Comment by sandbergja** [comment]
[This documentation of the figgy integration](https://github.com/pulibrary/orangelight/blob/main/docs/orangelight-figgy.md) will be helpful for whoever is looking at this ticket.

**Comment by maxkadel** [comment]
Note - this should be tested on the QA environment, since it cannot be replicated on staging (probably because of the figgy environment or something similar)

**Comment by maxkadel** [comment]
An example that's already in the test data is https://catalog.princeton.edu/catalog/9968683243506421 (as far as I can tell)

**Comment by kevinreiss** [comment]
Need some clarification on how the desired outcome for maps relate to the display and behavior of non-map Multi-volume works.

**Comment by maxkadel** [comment]
@tpendragon @eliotjordan  - am I understanding correctly that multi-volume works should have multiple viewers, but "ScannedMap" (per graphql) resources should have a single viewer?

**Comment by tpendragon** [comment]
@maxkadel For documentation, https://github.com/pulibrary/orangelight/pull/3286 is the PR where I broke this.

I think it's this:

If I get back two resources and one of them is in the `member_ids` of another, don't display the child.

There's never a case where we want to display the MVW manifest -and- the volume manifest on the same page.

**Comment by maxkadel** [comment]
@tpendragon That PR is part of why I'm confused. 

### Scenario 1 - 1 physical object with 2 Figgy records, one for regular imaging, one for multi-spectral imaging
So, https://catalog.princeton.edu/catalog/9950403683506421 should still have 2 viewers after whatever changes I make, since there is 
* 1 physical object with a recto and verso
* 1 catalog record for that object
* 2 Figgy objects
  * 1 Figgy object is a simple object (not nested) with 2 images, one of the recto and one of the verso, which translates to one iiif viewer (see https://figgy.princeton.edu/catalog/bbc6f6c4-3b92-4ae9-8461-1a14c113af8c)
    * This is represented in the iiif manifest as `@type: "sc:Manifest"`
  * 1 Figgy object is a complex object with two nested "members" (see https://figgy.princeton.edu/catalog/54b399c7-f28c-46f6-a7b4-c835a60516c4)
    * Each "member" is a set of multi-spectral images
    * Both members are represented in a single iiif manifest as `@type: "sc:Collection"`, resulting in a single viewer

### Scenario 2 - 1 map in 6 sheets and 1 Figgy record
https://catalog.princeton.edu/catalog/9968107933506421 - Should have a single viewer after whatever changes I make
* 1 conceptual object in six pieces (1 map, 6 sheets)
* 1 catalog record
* 1 Figgy object
  * Complex object with 7 nested "Child Scanned Maps" (one for each sheet, plus one of all of the sheets digitally stitched together)
  * Each manifest that Orangelight fetches has `@type: "sc:Manifest"`. The one that has all of the images has multiple canvases under Sequences: Canvases, whereas the single images on have on canvas.

So, could we say that the number of viewers should match the number of Figgy objects?
