### ISSUE TITLE
Deprecation warning: Calling show_fields_for with a scalar value is deprecated

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/orangelight#3490]
Seen when running the test suite:

```
DEPRECATION WARNING: Calling show_fields_for with a scalar value
is deprecated. It must receive an Enumerable. (called from
_app_views_catalog__show_top_fields_html_erb__4288495172432519664_78100
at /home/circleci/orangelight/app/views/catalog/_show_top_fields.html.erb:5)
```

**Comment by maxkadel** [comment]
It looks like this is being raised because `document['format']` for https://catalog.princeton.edu/catalog/SCSB-7935196 is nil. It seems wrong that the format would be nil - should we ever expect to get nil for format?

I'm trying to figure out how to see what we're getting from SCSB for that record, and why the format might be nil - we might need to change something in Bibdata as well.

**Comment by maxkadel** [comment]
See https://github.com/pulibrary/bibdata/issues/2134 for ticket for work without format
