### ISSUE TITLE
Scanned map resource bounding box is not being generated in json-ld view

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#3496]
Record:
https://catalog.princeton.edu/catalog/9941463973506421.jsonld (no `coverage` property)
https://bibdata.princeton.edu/bibliographic/9941463973506421

vs. Working Record:
https://catalog.princeton.edu/catalog/9977102743506421.jsonld
https://bibdata.princeton.edu/bibliographic/9977102743506421

034 field on 9941463973506421 appears to be fine.
This is keeping the record from being indexed into Pulmap.

This record does not have an bounding box (`coverage`) available in the Orangelight JSONLD view. DACS is supposed to do a re-index of the catalog next week (3/13) which we think will fix the problem. 

- [x] Fix so the coverage value is included in the JSONLD
- [x] Refresh the Figgy resource with the new metadata (DLS can do this)
   - https://figgy.princeton.edu/catalog/80e4bc5f-876d-44c5-8e6d-dc882647a891 
- [x] Let Wangyal know.

**Comment by maxkadel** [comment]
The example jsonld does not have a `coverage` property because the object's Solr record does not have a `coverage_display` property. ([working record solr doc](https://catalog.princeton.edu/catalog/9977102743506421/raw), [not working record solr doc](https://catalog.princeton.edu/catalog/9941463973506421/raw))

See [ticket in Bibdata](https://github.com/pulibrary/bibdata/issues/2135)

**Comment by maxkadel** [comment]
In the end the issue was a hidden character in the record, which @mzelesky removed (thanks Mark!) and the jsonld is not populating correctly.
