### ISSUE TITLE
Toggle Aeon Base URL via Feature Flipper

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3676]
The current aeon_base value should be set to this temporary test URL (for use only in staging and QA). 

```https://princeton.aeon.atlas-sys.com/logon```

When the new system goes live it will be 

```https://lib-aeon.princeton.edu/logon```

Th existing production base URL (this needs to remain in place until the morning of the migration). 

```https://lib-aeon.princeton.edu/aeon/aeon.dll```

The querystring also needs to be updated in the fashion you see in this commit: https://github.com/pulibrary/orangelight/pull/3675/commits/2aa7ab8ad5619fc6e07a4732167f45d1962cf6dc. 

The following two params need to be added to be the test and the current "OpenURL?" needs to be removed from the querystring. 
```
Action=10&Form=30&
```
The full base with the new required query string params looks like: https://lib-aeon.princeton.edu/logon?Action=10&Form30.
```

This method likely needs to be re-factored: https://github.com/pulibrary/orangelight/blob/ffcff4bbad555d8a7a2d862bc43f947071cb11d4/app/models/requests/aeon_url.rb#L14

**Comment by sandbergja** [comment]
Possible approach:

* Each environment has two url configurations: one for self-hosted, one for Atlas-hosted
* The feature flipper would enable us to switch between self-hosted and atlas-hosted (which would be the test environment for staging/qa, the new prod environment for prod)
 
We also should find a way to test against the new production so that we are confident when it goes live.
