### ISSUE TITLE
"previous" and "next" navigation buttons do not remain when looking through catalog records from a list of results

### ISSUE THREAD

**Issue by caroldh** [pulibrary/orangelight#4566]
### Expected behavior
I would expect that navigation buttons remain as an option, so that I can continue to view next (or previous) records in my list of results. 

### Actual behavior
I have a list of search results, and when I click into the 1st record, I can see the  "previous" and "next" available for me to navigate through the list. But if I click "next" to view the next record in the list, I no longer see the "previous" and "next" buttons. 
1st record, where navigation is possible:
![{400431BF-1B8C-430E-8BFA-A05559CBA262}](https://github.com/user-attachments/assets/fe4a1222-8749-48a5-827e-6bed998fb828)

After clicking "next" to see next record, buttons are no longer available:
![{64E94009-F76C-4EB4-98E1-FD1EDF9E796E}](https://github.com/user-attachments/assets/f2e68d94-c595-47ad-9c95-69d16ec2b31f)

### Steps to replicate
Execute a search in catalog and get a list of results. Click on one of the records, and use "previous" or "next" to move in the list of results. On next record, you will no longer see options for "previous" or "next"

### Impact of this bug
Cannot easily move through a list of search results.

[Related Slack thread](https://pulibrary.slack.com/archives/C031U4XCUH2/p1731683169255359)

**Comment by christinach** [comment]
The render of the 'SearchContext::ServerItemPaginationComponent' that includes the Previous and Next links does not happen because one of the conditions `(@search_session['document_id'] == @current_document_id)` in the [def render ](https://github.com/projectblacklight/blacklight/blob/1494bd0884efe7a48623e9b37abe558fa6348e2a/app/components/blacklight/search_context/server_item_pagination_component.rb#L14)method returns false. 

Example of the UI with debugging the output:
![Previous and Next links display](https://github.com/user-attachments/assets/f1ab65b1-5c04-46c1-9e2c-a63b0466b701)
When the search_session is not updated with the current document.id 
![Previous and next dont display](https://github.com/user-attachments/assets/e55efafe-398f-4a99-be93-b9e73a7b178d)

Nothing seems to have changed in the Blacklight::SearchContext module and specifically in the [def session](https://github.com/projectblacklight/blacklight/blob/1494bd0884efe7a48623e9b37abe558fa6348e2a/app/controllers/concerns/blacklight/search_context.rb#L56) 

Could this be a rails change in the actionpack that handles indifferentAccess or maybe we override something in the catalog that I haven't found yet. 

@sandbergja @maxkadel @rladdusaw you all worked the last 2 weeks finishing the upgrade. Did you notice a change in the search_session?
