### ISSUE TITLE
Blacklight 8: Pagination in Bookmarks page does not work

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4568]
### Expected behavior
When I view the bookmarks page I can click on the pagination to view them.

### Actual behavior
When I view the bookmarks page and I click on the pagination to view them I get the error page 'Looks like something went wrong'.

### Steps to replicate
1. Checkout the blacklight 8 branch
1. Bookmark more than 10 books.
1. Go to https://catalog.princeton.edu/bookmarks?per_page=10.
1. Click the second page in the pagination.

### Impact of this bug
The user cannot paginate through the bookmarks.

Related ticket: #4566

**Comment by maxkadel** [comment]
Since I am leaving for the week, I'm putting this back down.

I wrote a [test that fails against Blacklight 8](https://github.com/pulibrary/orangelight/pull/4612) and passes against Blacklight 7. 

On blacklight 8, it seems that the request is going through the search_builder and hitting the [excessive_paging](https://github.com/pulibrary/orangelight/blob/8ddfbea8537489bde0a85779db72793f8b5fb06b/app/models/search_builder.rb#L76-L90) checks, which raises an error.

My best guess is that this is because either
a) In Blacklight 7 it doesn't go through the search_builder in the same way, and so doesn't hit those checks, or
b) In Blacklight 8 it's not getting passed with its full context, and so fails those checks.
