### ISSUE TITLE
[Advanced Search] Language facet will only display some of the indexed languages

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#4597]
### Expected behavior
When I type a language in the advanced search/language facet I the combobox to start showing languages that are from indexed resources. 

### Actual behavior
When I type "Khmer" in the advanced search/language facet the combobox can't find the language even though there are indexed [bibliographic resources in the catalog](https://catalog.princeton.edu/?f%5Blanguage_facet%5D%5B%5D=Khmer&q=khmer&search_field=all_fields)

### Steps to replicate
Go to https://catalog.princeton.edu/advanced
click in the 'Language' input field
Start typing 'Kh'
Khmer doesn't come up.

### Impact of this bug
Users cannot use the advanced search successfully to filter on a specific language.

Reported by [Minjie in the catalog channel](https://pulibrary.slack.com/archives/CA0UY0Q07/p1732199494157179).

**Comment by maxkadel** [comment]
Putting this back because I'm leaving for a week.

I think what's happening is that the old advanced search gem allowed you to configure advanced search facets completely separately from other facets. 

Now they share the same configuration, so if we want to limit the number of facets displayed on the regular search (which I think we do because it can have a very long tail), then that also limits the number of facets displayed on the advanced search, but then the advanced search doesn't have the "more" button that the regular search has.

They are both currently [configured in the catalog controller on a single line](https://github.com/pulibrary/orangelight/blob/8ddfbea8537489bde0a85779db72793f8b5fb06b/app/controllers/catalog_controller.rb#L125).

We also still have some[ "advanced_search" facet configuration](https://github.com/pulibrary/orangelight/blob/8ddfbea8537489bde0a85779db72793f8b5fb06b/app/controllers/catalog_controller.rb#L42-L47) in the catalog controller, but as far as I know it no longer has any effect (and we should probably remove it, unless we can find a way to make it actually change the controller's behavior).
