### ISSUE TITLE
Feedback: Links to Full text missing

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#488]
Voyager links to Google Books Search when full text is available. It looks like Umlaut can get us that + Hathi and Open Library, which seems like a good idea.

**Comment by escowles** [comment]
@kevinreiss We thought you knew about this.

**Comment by kevinreiss** [comment]
@escowles, Umlaut does have existing adaptors for GBS, Hathi, and Open Library (though that one needs some help and has overlap with Internet Archive per the code comments in the adaptor file), https://github.com/team-umlaut/umlaut/tree/master/app/service_adaptors. Hathi and GBS are current enabled in our dev and production umlaut instances. Orangelight uses the routine at https://github.com/pulibrary/orangelight/blob/development/app/views/catalog/_show_main_content.html.erb#L20 that uses Umlaut's https://github.com/team-umlaut/umlaut/wiki/JQuery-Content-Utility to render matching full_text services under certain conditions. Right now the the urlfy helper referred to in #499 suppresses this call except when the title is a Princeton e-journal holding via the ```data-umlaut-fulltext``` attribute. If we undo that any full-text matching services Umlaut finds will be returned. However there are two negatives:

1. Before relying on Umlaut to reliably resolve full-text services in the services under discussion we need to review Blacklight's current method of generating OpenURLs, open in #256. Many of the desirable titles in the OPAC that can full-text matches are older, non-ISBN resources that we need to make sure pass optimal metadata for over to Umalut. @tampakis and I were thinking we'd want to replace what currently does [see https://github.com/pulibrary/orangelight/blob/development/config/initializers/blacklight_initializer.rb#L21] this with a routine that normalizes an OpenURL into a solr document. That code is a minor modification of a default routine that lives in blacklight-marc. We may also need to tweak the service adaptors so that they don't try and return responses as full-text matches when the OpenURL has undesirable characteristics. When we initially deployed this for the OL dev committee last Fall and umlaut full-text services were active for all Marc records we had complaints about false positives from OpenURLs that did not include standard numbers. 
2. Slow response times from the SFX full-text service. Umlaut checks all possible options by default when an OpenURL is sent to it. Issue #256 shows how slow this service can be when the OpenURL isn't specific enough. For many of the Marc Records in the collection passing over an OpenURL that contains only minimal metadata it would be best to figure out a way avoid a call to SFX entirely.

**Comment by kevinreiss** [comment]
Short addendum. Looking at the APIs for Haithi, Google, Open Library it seems the best thing we can do is make sure that LCCNs, ISBNs, and OCLC Numbers are properly identified and included in the OpenURL.

**Comment by jpstroop** [comment]
Are we able to do this or not?

**Comment by kevinreiss** [comment]
There is nothing that would prevent us from trying other than time.

**Comment by jpstroop** [comment]
I think the OCLC # approach is fine. Can we hit Google this way as well?

**Comment by kevinreiss** [comment]
Yes, responses from Google should come back if the metadata has an oclcnum, isbn, or issn that will work. However results can be uneven. These are three examples of volumes in Hathi/Google from an old issue RBSC filed with me. My initial example has only Hathi services:  http://getit.princeton.edu/go/8016. This one has both Google/Hathi: http://getit.princeton.edu/go/8029.  And this one has neither: http://getit.princeton.edu/go/8028. 

Whatever set-up we do on the OL side should only make a call to umlaut when we've got some standard numbers to try and match. When it doesn't have those Umlaut will fail back to title and author level searching which can produce false matches. 

Each block of content on the umlaut menus has a service "key" mapped to an ID you'll find in the html. They are pretty much what you'd expect: "fulltext", and "excerpts" are the ones we probably want to try.  "cover_image", "search_inside", and "excerpts" also seem like the ones we may want to look into. The documentation of what we are using in OL in limited way right now with the full-text Journals is https://github.com/team-umlaut/umlaut/wiki/JQuery-Content-Utility.
