### ISSUE TITLE
Patron-specific checked out status messages

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#502]
In Blacklight the item appears as checked out/unavailable because the
item is charged - https://pulsearch.princeton.edu/catalog/9232733

However, in Voyager the item has a status of "On MENDEL NEW BOOK SHELF"
- http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=9232733

Mendel new book items should have status "On shelf." These items are publicly accessible and can be checked out. Hopefully this can be accomplished by setting up a new temporary location code for cases like this, unless if there are a lot of these special patrons configured to have custom status messages when books are checked out by them.

**Comment by joycebcat** [comment]
They get this note in Voyager by charging the material to a pseudo-patron.  It is going to show as unavailable because it is actually charged out.  The lesson here is probably that there is a use case for indicating temporary locations--why he isn't using the item temp location for this, I don't know, that is what it is meant to do.  I think might be a change of procedure rather than programming blacklight differently.

**Comment by kevinreiss** [comment]
@joycebcat Do you have any idea where the string value displayed in Voyager's Status field might actually come from? I looked through whatever custom code we have that does some re-writing of the Web Voyager page and came up empty.

Yes a temporary location would be a much better thing to do to manage the New Book shelf. The current "request" options we display to patrons encourage users to try using Borrow Direct to get the item because the item status is "Charged.". That has been in place for at least four years.......

**Comment by joycebcat** [comment]
@kevinreiss See the message I sent shortly before yours.

**Comment by joycebcat** [comment]
@kevinreiss That is all I know.  The item is charged to a patron with the name "MENDEL NEW BOOK SHELF".  Since that is what is appearing, there is obviously some connection.  I don't know any more about how it turns into a status note.

**Comment by kevinreiss** [comment]
Okay, thanks @joycebcat . That is helpful and something to start with. There must be some ancient customization buried somewhere that is reading the charged patron name and inserting that value.

**Comment by mzelesky** [comment]
I'm doing some digging. I'll tell you what I find. I spoke to Joan about it, and she said there are multiple branch libraries that use this type of workaround. She recommended bringing up this workflow at LISSC.

**Comment by mzelesky** [comment]
Ok, so we assumed it was a fancy workaround we developed in-house. It turns out it is built-in functionality of Voyager. You check a box in Voyager Sys Admin for the patron group that says 'Display OPAC Messages for charged items' and define the status display in opac.ini.

I see no specific query that does this, but it would require querying the 'CIRC_TRANSACTIONS' table for every item attached to a bib. Utilizing the temp location instead of charging the item to a pseudo-patron makes sense to me, especially if the items can be charged to any patron that wants them. The Architecture and Music Libraries are the only 2 locations that use this. One patron in the group is 'UES Staff Office Reserve'. I guess the idea is that circ staff are used to charging and discharging items, and adding a temp location is a new task. With Pick & Scan, though, maybe it's easier to do now than it used to be.

**Comment by kevinreiss** [comment]
I also agree that the temporary location code is the way to go. Baking in some obscure behavior for a feature used by only two of our locations seems something likely to be difficult to maintain especially when there is a perfectly functional alternative.

**Comment by tampakis** [comment]
These items should no longer be checked out to new books patrons.
