### ISSUE TITLE
Include $i note for linked record

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#595]
This might be difficult to accommodate given how the the linked fields work. The 776 is appearing under "Other version(s)," but the display value is taken from the Solr matched response (to make sure that the links actually work). Ideally the $i note would display before the linked record.

> 776 (with subfield i note) not appearing
> example: Mountain geologist (bib 567332)
> 
> Since a recent change to serial cataloging guidelines, 776 is used instead of 785 when a serial ceases in print, continued online only. In these cases a note (e.g. "Continued online only") is recorded in 776 subfield i. This note currently appears in neither the existing catalog nor the Beta catalog, but it would be good if it could.

**Comment by jpstroop** [comment]
From @jbaxmeyer

>I can’t transfer this ticket to you directly from LibAnswers, so I’m forwarding it instead. Information coded in the MARC 776 field doesn’t display in Blacklight. This causes confusion for patrons, plus extra work for us to investigate “problems” that are not actually problems. Please see also [this issue]. Are linked fields still a problem in Blacklight? 

Original Issue:

> ... the main problem is that the public catalog (both old and new) does not display 776 notes that are coded for display (first indicator zero). In cases of a cease with a format change (e.g. print to online), the "continued by" information goes only into the 776 field.

**Comment by christinach** [comment]
We're indexing 776i. @mzelesky do we want to display this info in the catalog?

**Comment by mzelesky** [comment]
This would be affecting the "Other Versions" section, right?

**Comment by mzelesky** [comment]
My question would be if all of the links would still be in the "Other Versions" box, or if there would be different boxes for different `$i` values.

**Comment by christinach** [comment]
@ellen-aa @caroldh can you please review this ticket ?

**Comment by christinach** [comment]
We will discuss this ticket during the Orangelight meeting on Thursday 8/29/2024.

**Comment by mzelesky** [comment]
There are a total of 1,023,691 776 fields with subfield i. Tally of bibs by $i value (top 10):
`Print version:`: 421,657
`Microfiche version:`: 310,859
`Online version:`: 119,507
`Source record:`: 72,961
`ebook version :`: 19,339
`Print manuscript version`: 16,639
`Microfiche`: 14,398
`Print version : `: 6,582
`e-book version`: 5,434
`Print version: `: 5,340

The top 10 account for 96.9% of all 776 fields with subfield i.

There are also numerous typos in the 776$i, along with titles and ISBNs (e.g., `Ppaer version:`, `Print versiont:`, `Online versio:`) . I think it would only add noise to the record view, since it's entirely possible that even though the 776$i may say the print version is the other record, there may be electronic inventory on the other record (or vice versa).

**Comment by christinach** [comment]
We decided to close this ticket as it doesn't bring value. 
Orangelight meeting 9/5/2024
