### ISSUE TITLE
Vertically center availability label in search results

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#608]
When the holding info is two lines it doesn't look well-aligned with the availability label. Is it possible vertically center the availability label?

Example scresnshot:
![two_line_label](https://cloud.githubusercontent.com/assets/4650153/16249437/c74f07d4-37e3-11e6-9fa9-86e2d6c19d27.png)

**Comment by axamei** [comment]
Truncate long call numbers. @tampakis

**Comment by joycebcat** [comment]
I hope when you consider truncating long call numbers, you don't mean to remove anything from the actual call number, right?  You might truncate the text for the location.

**Comment by tampakis** [comment]
We're considering truncating call numbers like in the first result of this search: https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=Richard+Hand+at+the+Kings+Arms+at+Chelsey+%5Bplate+and+print%5D

**Comment by joycebcat** [comment]
Ah.  This does make sense.  These long strings with slashes in them are from Graphic Arts.  Users can't retrieve the material themselves, so not having the full call number on the result screen isn't going to make much difference.  I am concerned that a user might see a partial call number in the results and go running to a shelf and not be able to find the material because they didn't have the full number.
