### ISSUE TITLE
How do we react when we find incorrect Google Book covers?

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#624]
Apparently Stanford first checks to see if the incorrect cover image is due to a cataloging error and then reports the issue to [Google Books](https://support.google.com/books/troubleshooter/6113172?hl=en&rd=2) an ISBN/ISSN/LCCN/OCLC number is incorrectly matched to a book. What should our protocol be?

Maybe we should add a page similar to [Stanford's](https://lib.stanford.edu/searchworks/why-are-cover-images-sometimes-wrong) on our help page.

Beta feedback 1 for incorrect [Google Book match](https://books.google.com/books?id=3TzwC4likFoC&dq=lccn05025909&hl=&source=gbs_api) on correct LCCN:
> The book image for this record Life of Thomas Telford https://pulsearch.princeton.edu/catalog/1380014 is very incorrect.

Beta feedback 2 for incorrect Google Book image on correct [ISSN match](https://books.google.com/books?id=upiVngEACAAJ&dq=issn:0009840X&hl=&cd=2&source=gbs_api):
> the Google image for “Classical Review” was for the book “The Ages of Homer,” which has nothing to do with Classical Review. https://pulsearch.princeton.edu/catalog/565782

**Comment by jpstroop** [comment]
> Maybe we should add a page similar to Stanford's on our help page.
:+1:

**Comment by jpstroop** [comment]
Maybe a tiny link under under each cover thumbnail? Or is that overkill?

**Comment by tampakis** [comment]
I just "reported an incorrect cover image" by clicking on the feedback link from Stanford's record: https://searchworks.stanford.edu/view/2933973

**Comment by joycebcat** [comment]
I got an e-mail about an incorrect cover.  I know this is going to happen, but this particular instance  appears because you changed the programming awhile back to use LCCN as a matching point.  Do you have any information about how accurate the LCCN matching is for getting the right image?  Does the procedure for reporting them need to be any different?

**Comment by jpstroop** [comment]
It's annoying, but I suspect this is the channel:
https://support.google.com/books/partner/troubleshooter/2983879

**Comment by joycebcat** [comment]
I got another report from Darwin about a jacket.  It turns out the LCCN of the wrong image is the same number with a "bl" prefix.  In olden days (pre-2001) LCCNs could have a prefix and otherwise be identical.  If we continue to use LCCN, we have to distinguish based on the whole string, not just the number. --Joyce


Wrong book cover showing for Dance : American art, 1830-1960 
Please see https://pulsearch.princeton.edu/catalog/9574698 -- the wrong book cover is showing.
Darwin

**Comment by tampakis** [comment]
See #703

**Comment by tampakis** [comment]
Wow one of the reported incorrect google covers mentioned in this issue was fixed! https://pulsearch.princeton.edu/catalog/565782
