### ISSUE TITLE
Old on-order records

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#721]
Some records never had item records created but have acquisition records dating back from 2000: https://pulsearch.princeton.edu/catalog/697954

If an order is old enough should we change the status to `Item on shelf`? That's what the fall back value is for records with no item records or acquisition records.

**Comment by joycebcat** [comment]
@tampakis No, this we can't do.  Just because we have ordered something doesn't mean it will always arrive. We may never actually acquire the item.  The example you cite is one where we do seem to have received something, but that may not always be the case.  What I think this means is that we have more cleanup work we need to do.  Sigh (although this one isn't my problem, hooray!).  Is this something that you can report?  If not, no problem, I'm sure Carol can get something out of Voyager.
