### ISSUE TITLE
Schedule Guest User Cleanup Task

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#787]
Devise-guests creates a new DB row for every anonymous session. Need to schedule rake task
```rake blacklight:delete_old_searches[days_old]```
in cron. 7 days seems reasonable.

**Comment by tpendragon** [comment]
What server should the cron run on?

**Comment by tampakis** [comment]
So the cron is set up on lib-orange-prod2, but it doesn't work right now because there are just way too many searches (25 mill) and guest users (13 mill). The task gets killed because it runs out of memory. After the old searches get flushed then I think we'll be good to go. Probably a good idea to run daily.

**Comment by tampakis** [comment]
Cleared out the bulk of the searches directly in the db. Now down to 200,000 searches and 440,000 users. The searches and users tables are now small enough to support running the rake task cron job daily.

**Comment by jpstroop** [comment]
Is this something that could be set up with the ansible playbook? I guess we only need one machine running it; seems like a pain to have to remember to set it up.
