### ISSUE TITLE
Strip out enumeration info from linked fields during indexing

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#800]
(In marc liberation traject code)
ISBNs formatted like `9780160833083 (pt. 1)` don't get included in the linked "other versions" field because they can't be be parsed as ISBNs (due to the enumeration info the parentheses following the number).

**Comment by joycebcat** [comment]
@tampakis Nikitas, the ISBN that appears in a 776 or 787 field is one that applies to the related work referenced in the field.  In the case of the 776 it is an ISBN for a different physical version of the same work, but for the 787 it is just something related somehow.  These numbers do not belong in an 020 |z on the record (although long-standing practice with e-books has been that the other physical version ISBN is often given in that field)

**Comment by tampakis** [comment]
Thanks for the info @joycebcat. I thought that the 776 |z was the place to put ISBNs for a different physical version of the same work. That's the field we check for linking to other versions based on ISBN.

We also include the 787 |w in the other versions links. We check for bib id and OCLC number matches in subfield $w, but if we wanted to we could also include the 787 |z for ISBNs of related entries.

**Comment by joycebcat** [comment]
@tampakis I'm wondering if I misunderstood what you meant with your original message.  Are you saying that some ISBNs are miscoded *within the 776* because they are coded |w in the 776 instead of |z in the 776?  That is indeed a problem.  ISBNs for other versions belong in |z of the 776/787 as appropriate.  I'm not sure how well you would be able to include miscoded ISBNs by using the |w because there are a lot of other numbers appearing in that subfield.
