### ISSUE TITLE
Include 520 $c

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#813]
I've noticed that these have been stripped, e.g.: https://pulsearch.princeton.edu/catalog/9982236

I think this is a newer practice; may be the case for all notes (or at least more than just the 520). @joycebcat ?

**Comment by joycebcat** [comment]
Interesting.  I hadn't seen this subfield in use before.  I think 520 is the only 5xx it relates to.  Some other 5xx have a subfield c defined, but it means something different.  There has been concern over the bias and language used in some of these 520 fields amongst catalogers but I haven't gotten any user complaints here yet.  I would love to have the subfield display in BL so that I never do get any.
