### ISSUE TITLE
Lowercase q in accession numbers

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#863]
From feedback:
>  Call no. search/browse fails on RBSC accession nos., such as Rare Books » Oversize item 5759289q (https://pulsearch.princeton.edu/catalog/6134266). 

Why do accession numbers have qs at the end of them?

**Comment by tampakis** [comment]
Oh wati, the normalizer actually already handles that case. Not really sure what the issue is here. I'll wait for more info before closing.

**Comment by joycebcat** [comment]
Hi Nikitas, call numbers have a "q" on the end when they are oversize.  They get shelved in a different sequence when they are oversized, so the q is important.  If you need more info about q in combination with accession numbers, you should ask Don Thornbury since this only happens in RB where they aren't assigning call numbers.

**Comment by tampakis** [comment]
Hi @joycebcat, ok thanks for that info. I didn't know the "q" extended to accession numbers, but I actually checked the normalizer output and we actually handle that case correctly (at least in a virtual browse sense).

The issue Darwin came across was that the search had to include "item" along with the accession number. He wasn't expecting them both to be grouped together and searched for: https://pulsearch.princeton.edu/browse/call_numbers?q=5759289q

instead of: https://pulsearch.princeton.edu/browse/call_numbers?q=item+5759289q

**Comment by joycebcat** [comment]
@tampakis  "item" in this case is actually part of the call number just as we use "DVD" and "microfilm" as prefixes for other accession numbers.  Darwin should be used to that since he has DVD and things of that nature in his collection.  The other link you provided goes to things in a different call number scheme--they aren't accession numbers.  I *think* (but am not completely sure) that all of our accession numbers use a prefix.

**Comment by tampakis** [comment]
Ok, so nothing we need to change then. Thanks
