### ISSUE TITLE
Records with invalid locations cause display errors

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#944]
Results and single record display don't work when the record contains an invalid location code.

Current example: https://pulsearch.princeton.edu/catalog/10410213/staff_view

Results error: https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=10410213
Single record display error: 
Current example: https://pulsearch.princeton.edu/catalog/10410213

**Comment by mzelesky** [comment]
See https://github.com/pulibrary/marc_liberation/issues/1

This might be best addressed by a workflow change with suppressing temp records instead of a coding change, as some locations are set to be suppressed locations for display in the old OPAC. This particular record has a valid Voyager location code, it is just a location that is never supposed to display even if a holding has the location.

**Comment by mzelesky** [comment]
I will bring this to Marie W. Many are likely errors.

**Comment by tampakis** [comment]
Just happened again with https://catalog.princeton.edu/catalog/1085341.json
