### ISSUE TITLE
Display Princeton holding before SCSB copies of same title

### ISSUE THREAD

**Issue by tampakis** [pulibrary/orangelight#992]
When there is a match on the OCLC/ISBN/ISSN in the search results with both a Princeton and SCSB copy, display the Princeton copy first.

**Comment by tpendragon** [comment]
For issues like this, can we get example records?

Theoretically this should be straight forward - just weight things from princeton higher.

**Comment by kevinreiss** [comment]
Here is a title search for one with quite a few editions that may be challenging https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=title&q=Capitalism%2C+socialism%2C+and+democracy.

**Comment by hackmastera** [comment]
How can I tell which is the princeton copy?

Also, not all records have a staff view. In the second example given above, the recap records don't appear to have a staff view, nor do the e-resources. what determines whether something has a staff view?

**Comment by kevinreiss** [comment]
Any record that has a numeric ID in the solr index comes from Voyager and I think are the "Princeton Records" we were requested to boost here. All the voyager records should have a staff view because those are the only ones we can provide Marc data on demand for. The e-resources that come from Voyager should also have the staff view so if we are not seeing that on something with a numeric ID than there is something amiss with that record. Besides the SCSB- records the other data sources are senior theses (all start with the "dsp" prefix) and the graphic arts database that start with the "visuals" prefix.

**Comment by kevinreiss** [comment]
These two examples (which I pulled from user feedback) are pretty challenging though. Getting them sorted correctly seems pretty challenging. Looking more this example https://pulsearch.princeton.edu/?f%5Bformat%5D%5B%5D=Journal&q=American%20Political%20Science%20Review&search_field=all_fields the e-resource that the staff member complained about being buried (record 6 https://pulsearch.princeton.edu/catalog/9773162) has a different ISSN than the ones that appear before it so unless we want to go through and try to identify equivalent ISSNs in search results I'm not sure how that record would elevated up in the hit list.

**Comment by hackmastera** [comment]
can we just slightly elevate anything with a numeric ID?

**Comment by kevinreiss** [comment]
We could try that. I think that would work for the most straightforward cases where you have two or three records that are exactly the same edition/serial.

**Comment by hackmastera** [comment]
I'm looking into function queries and I think we need to index a new field, because I don't see an existing regex matcher.

We could probably write a custom function to do a regex match but this seems comparatively outside the norm for what we tend to do, and solr docs suggest that indexing a numeric boost value is preferred:
"Using Field and/or Document boosts has been supported since the very early days of Lucene, but is some what limiting and antiquated at this point, and instead people should strongly consider indexing their boost values as numeric fields instead" [https://wiki.apache.org/solr/SolrRelevancyFAQ#index-time_boosts]

**Comment by hackmastera** [comment]
So if we get a new boolean field indexed into solr we can mess around with the right boost level in edismax. It could look something like `if(field(numeric_id_b),100,0)`.

Then if we decide we like it we can put it in the default request handler configuration in solrconfig.xml like `<str name="boost">if(field(numeric_id_b),100,0)</str>` although there is probably a way to put this in the blacklight `SearchBuilder` instead. If that is preferred, please let me know.

**Comment by tpendragon** [comment]
Do we do request boosting now? I thought they had performance implications.

**Comment by escowles** [comment]
Can we test the performance of request boosting?  This seems like a good approach to me if there's not a big performance impact.

**Comment by hackmastera** [comment]
I'm not sure how to test performance impact other than reindexing on staging with the field in place.

I'm also not sure what you mean exactly by "request boosting". Do you mean using the edismax "boost" parameter per se? Or do you mean boosting at query time at all? If the latter, various boosts are done in the default requestHandler here: https://github.com/pulibrary/orangelight/issues/992#issuecomment-356744342

**Comment by tpendragon** [comment]
I meant the latter. If that's the case, :+1: to the boolean.

**Comment by hackmastera** [comment]
oops, clipboard fail. I corrected the link in my prev. comment.

**Comment by escowles** [comment]
@hackmastera I was mostly thinking that you could test the performance impact of adding a boost parameter based on some other existing boolean field.  But if we're already doing boosting, then this is probably not necessary.

**Comment by hackmastera** [comment]
@escowles I can try a few searches with / without the extra boost and report back once I get the field indexed.

**Comment by kevinreiss** [comment]
Here is another example that came for some staff comments awhile back, https://pulsearch.princeton.edu/?page=1&q=envisioning+information&search_field=all_fields&utf8=%E2%9C%93.

**Comment by hackmastera** [comment]
@tampakis and I discussed whether there might be a solution to this problem that allowed us to swap the position of individual results based on matching control numbers (oclc, isbn, etc). We agreed that while we want to do careful testing of a global boost, it is still the best way forward on this problem because it uses the tool we have (solr) in its intended way, whereas changing the order of results would be an exercise in fighting with solr. One particular concern is how such an approach would work with paged results retrieval. Another concern is discovering an efficient algorithm (naive implementation is O(n^2)). It may be possible to limit this sort of post-results reordering to only happen when results sets are small, but how to identify that number? A low number would exclude many reported cases of this issue; a high number will introduce concerns about paging and eventually efficiency.

**Comment by hackmastera** [comment]
List of test searches:
* specific to this issue:
  * https://pulsearch.princeton.edu/?page=1&q=envisioning+information&search_field=all_fields&utf8=%E2%9C%93
  * https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=title&q=Capitalism%2C+socialism%2C+and+democracy
  * https://pulsearch.princeton.edu/?f%5Bformat%5D%5B%5D=Journal&q=American%20Political%20Science%20Review&search_field=all_fields
* Some standard exact title journal searches
  * Science
  * Nature
* some examples from the pul_solr relevance specs
  * cage silence
  * silence
* some random title, author searches
  * endgame
  * the man who mistook his wife for a hat
  * Naomi Klein
  * Henry Louis Gates Jr
* some random topic searches
  * society of friends
  * fermi paradox
  * literature during the industrial revolution

**Comment by hackmastera** [comment]
I'm gonna try this as a "bf" instead of a "boost". The boost multiplies the score, whereas the bf just adds to the score. So it should be more appropriate for bumping up the local holdings when scores are very very close (as expected / observed when they are different holdings of the same title).

**Comment by hackmastera** [comment]
Analysis of results for "plus 50" boost:

google docs folder with results data: https://drive.google.com/open?id=1mNKSR-ycXJSzsaYLnWp1f_tPn_TUr9f3

Ideally we hope that records representing the same title will have the same relevance score, so a small boost should be sufficient to bump our records above the others.

However, when there aren't very good exact matches for the term, and at the end of any result set (i.e. the last page of results), the scores will be lower so even a small boost will rearrange them.

I believe this is okay because the last page of results is already unlikely to be useful, whereas a small result set can be perused in full so a bit of a shift in relevance is tolerable.

In the data I looked at, a search with very good exact matches (see TODO) had scores in the hundreds of thousands, whereas a result set that didn't have good exact matches (see my results for "fermi's paradox") might have the most highly relevant score in the tens of thousands and scores near the bottom of the page in the hundreds and tens.

One interesting result was a search for "literature in the industrial revolution". The top 3 results were the same title. Before the boost was applied the 2nd result was a SCSB holding and the other two were princeton holdings. The difference between scores for results 2 and 3 was about 42. A boost much lower than 50 would have meant these two records would have stayed in the non-preferred order. This is a good reminder that sometimes a record may have a little extra metadata that gives it a higher score than a local record.

In all of the examples given as problems in this issue:
* boosting the electronic resource of "american political science review", above all the SCSB results would require 28,921.28 additional points. This doesn't seem achievable with a boost. It may be that we need more complete catalog records for electronic resources. Or more prominent placement of / more education about the 'electronic resources' facet?
* Results for "capitalism, socialism, democracy" were as desired for the journal result (top result) but not effective for the 2nd set of results, a book by Joseph Schumpeter.
* Results for "envisioning information" seem great.
 
The "society of friends" example rearranged a couple of titles, in one case they weren't the same title but they were very close in score so the switch seems negligable. In another case they were the same, and ours was bumped to the top. However, we also have a record for an electronic holding which remained the last of the 3 for this title; it would have required a boost of 75 to go above the SCSB holding. The scores for these records were around 200,000.

For keyword searches on author's names, some titles move around but they're all written by the author in question so it seems fine. The same goes for searches with lots of title exact matches.

**Comment by hackmastera** [comment]
This can be closed once orangelight is reindexed.
